// GENERATED by zig_build/tests/charstring_diff/extract_oracle.sh -- DO NOT EDIT.
// The pinned upstream C body of stringGlyphLength (src/c47/charString.c),
// renamed oracle_* so it links beside the Zig owner export for A5 diffing.
#include <stdint.h>

int32_t oracle_stringGlyphLength(const char *str) {
  int32_t len = 0;

  while(*str != 0) {
    if(*str & 0x80) {
      str += 2;
      len++;
    }
    else {
      str++;
      len++;
    }
  }
  return len;
}
