// GENERATED by zig_build/tests/charstring_diff/extract_oracle.sh -- DO NOT EDIT.
// Pinned upstream C of the charString glyph cluster (src/c47/charString.c),
// renamed oracle_* so it links beside the Zig owner exports for A5 diffing.
#include <stdint.h>
#include <string.h>
#define stringByteLength(str) ((int32_t)strlen(str)) // charString.h

// forward declarations (the cluster is mutually recursive)
int32_t oracle_stringGlyphLength(const char *str);
int16_t oracle_stringNextGlyphNoEndCheck_JM(const char *str, int16_t pos);
int16_t oracle_stringNextGlyph(const char *str, int16_t pos);
int16_t oracle_stringPrevGlyph(const char *str, int16_t pos);
int16_t oracle_stringLastGlyph(const char *str);

int32_t oracle_stringGlyphLength(const char *str) {
  int32_t len = 0;

  while(*str != 0) {
    if(*str & 0x80) {
      str += 2;
      len++;
    }
    else {
      str++;
      len++;
    }
  }
  return len;
}

int16_t oracle_stringNextGlyphNoEndCheck_JM(const char *str, int16_t pos) {    //Not checking for beyond terminator. Use only if no risk for pos > length(str)
  int16_t posinc = 0;
  if(str[pos] == 0) {
    return pos;
  }

  if(str[pos] & 0x80) {
    posinc = 2;
    if(str[pos+2] == 0) {
      return pos+2;
    }
  }
  else {
    posinc = 1;
    if(str[pos+1] == 0) {
      return pos+1;
    }
  }

  pos += posinc;
  return pos;
}

int16_t oracle_stringNextGlyph(const char *str, int16_t pos) {
  int16_t lg;

  lg = stringByteLength(str);
  if(pos >= lg) {
    return lg;
  }

  pos += (str[pos] & 0x80) ? 2 : 1;

  if(pos >= lg) {
    return lg;
  }
  else {
   return pos;
  }
}

int16_t oracle_stringPrevGlyph(const char *str, int16_t pos) {
  int16_t prev = 0;
  int16_t lg;

  lg = stringByteLength(str);
  if(pos >= lg) {
    pos = lg;
  }

  if(pos <= 1) {
    return 0;
  }
  else {
    int16_t cnt = 0;
    while(str[cnt] != 0 && cnt < pos) {
      prev = cnt;
      cnt = oracle_stringNextGlyph(str, cnt);
    }
  }
  return prev;
}

int16_t oracle_stringLastGlyph(const char *str) {
  int16_t lastGlyph;

  if(str == NULL) {
    lastGlyph = -1;
  }
  else {
    int16_t lg = stringByteLength(str), next = 0;
    for(lastGlyph=0;;) {
      if(lastGlyph >= lg) {
        next = lg;
      }
      else {
        next += (str[lastGlyph] & 0x80) ? 2 : 1;

        if(next > lg) {
          next = lg;
        }
      }

      if(next == lg) {
        break;
      }

      lastGlyph = next;
    }
  }
  return lastGlyph;
}

