#!/usr/bin/env bash
#
# Generate the C-vs-Zig differential oracle (Annex A5).
#
# Extracts the PINNED upstream C body of a self-contained pure function from
# src/c47/charString.c, renamed with an `oracle_` prefix, so the differential
# harness can compile the upstream C and the Zig port into one binary and
# byte-compare them over enumerated inputs. Keeping the oracle sourced from the
# real pinned file (not a hand copy) means an M10 pin bump that changes the
# function changes this oracle too -- which is exactly the divergence the
# differential then catches against the (re-ported) Zig owner.
#
# Run from the repo root; rewrites charstring_diff_oracle.c next to this script.
# The harness's self-check fails if the committed oracle is stale, so CI/the M10
# cycle re-runs this and commits the result.
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/../../.." && pwd)"
src="$repo_root/src/c47/charString.c"
out="$(dirname "$0")/charstring_diff_oracle.c"

# Brace-match the self-contained function out of the pinned source (K&R: the
# closing brace is in column 0).
body="$(awk '
  /^int32_t stringGlyphLength\(const char \*str\) \{/ { capture=1 }
  capture { print }
  capture && /^\}/ { exit }
' "$src")"

[[ -n "$body" ]] || { echo "extract_oracle: stringGlyphLength not found in $src" >&2; exit 1; }

{
  echo "// GENERATED by zig_build/tests/charstring_diff/extract_oracle.sh -- DO NOT EDIT."
  echo "// The pinned upstream C body of stringGlyphLength (src/c47/charString.c),"
  echo "// renamed oracle_* so it links beside the Zig owner export for A5 diffing."
  echo "#include <stdint.h>"
  echo
  echo "$body" | sed 's/^int32_t stringGlyphLength(/int32_t oracle_stringGlyphLength(/'
} > "$out"
echo "extract_oracle: wrote $out"
