const std = @import("std");

const c = @import("c_bindings");

const last_item = 2732;
const max_number_of_items = 1200;

const cat_status: u16 = 0x00f0;
const cat_fnct: u16 = 1 << 4;
const cat_menu: u16 = 2 << 4;
const cat_cnst: u16 = 3 << 4;
const cat_syfl: u16 = 8 << 4;
const cat_aint_upper: u16 = 9 << 4;
const cat_aint_lower: u16 = 10 << 4;
const eim_status: u16 = 0x0100;
const eim_enabled: u16 = 1 << 8;
const cmp_extensive: i32 = 2;

const FunctionPtr = ?*const fn (u16) callconv(.c) void;

const Item = extern struct {
    func: FunctionPtr,
    param: u16,
    itemCatalogName: [16]u8,
    itemSoftmenuName: [16]u8,
    tamMinMax: u16,
    status: u16,
};

const Glyph = extern struct {
    charCode: u16,
    colsBeforeGlyph: u8,
    colsGlyph: u8,
    colsAfterGlyph: u8,
    rowsAboveGlyph: u8,
    rowsGlyph: u8,
    rowsBelowGlyph: u8,
    rank1: i16,
    rank2: i16,
    data: [*c]u8,
};

const GenerationType = enum(u8) {
    dmcp = 1,
    pc = 2,
    both = 3,
};

const Error = error{
    FileOpenFailed,
    FileWriteFailed,
    TooManyItems,
};

extern const indexOfItems: [last_item]Item;
extern fn compareString(stra: [*:0]const u8, strb: [*:0]const u8, comparisonType: i32) i32;

pub export var funcOK: bool = false;
pub export var glyphNotFound: Glyph = .{
    .charCode = 0,
    .colsBeforeGlyph = 0,
    .colsGlyph = 13,
    .colsAfterGlyph = 0,
    .rowsAboveGlyph = 0,
    .rowsGlyph = 19,
    .rowsBelowGlyph = 0,
    .rank1 = 0,
    .rank2 = 0,
    .data = null,
};
pub export var calcMode: u8 = 0;
pub export var significantDigits: u8 = 0;
pub export var displayStack: u8 = 0;
pub export var Input_Default: u8 = 0;
pub export var exponentLimit: i16 = 0;

pub fn main(init: std.process.Init) !void {
    const allocator = std.heap.page_allocator;

    var args = try std.process.Args.Iterator.initAllocator(init.minimal.args, allocator);
    defer args.deinit();

    _ = args.next();
    const output_path = args.next() orelse {
        std.debug.print("Usage: generateCatalogs <output file>\n", .{});
        std.process.exit(1);
    };

    const c_output_path = try allocator.dupeSentinel(u8, output_path, 0);
    defer allocator.free(c_output_path);

    const file = c.fopen(c_output_path.ptr, "wb") orelse return error.FileOpenFailed;
    defer _ = c.fclose(file);

    try writeAll(file, "// SPDX-License-Identifier: GPL-3.0-only\n");
    try writeAll(file, "// SPDX-FileCopyrightText: Copyright The WP43 and C47 Authors\n\n");

    try writeAll(
        file,
        "/********************************************//**\n" ++
            "* \\file softmenuCatalogs.h\n" ++
            "***********************************************/\n\n",
    );

    try writeAll(
        file,
        "/***********************************************************************************************\n" ++
            "* Do not edit this file manually! It's automagically generated by the program generateCatalogs *\n" ++
            "************************************************************************************************/\n\n",
    );

    try writeAll(file, "#if !defined(SOFTMENUCATALOGS_H)\n");
    try writeAll(file, "  #define SOFTMENUCATALOGS_H\n\n");

    try writeAll(file, "  /*<--------- 6 functions --------->*/\n");
    try writeAll(file, "  /*<---- 6 f shifted functions ---->*/\n");
    try writeAll(file, "  /*<---- 6 g shifted functions ---->*/\n");

    try writeAll(file, "  #if defined(DMCP_BUILD)\n");
    try emitMenu(file, "FCNS", cat_fnct, .dmcp);
    try writeAll(file, "  #else // !DMCP_BUILD\n");
    try emitMenu(file, "FCNS", cat_fnct, .pc);
    try writeAll(file, "  #endif // DMCP_BUILD\n");

    try emitMenu(file, "FCNS_EIM", cat_fnct, .both);
    try emitMenu(file, "CONST", cat_cnst, .both);
    try emitMenu(file, "SYSFL", cat_syfl, .both);
    try emitMenu(file, "alpha_INTL", cat_aint_upper, .both);
    try emitMenu(file, "alpha_intl", cat_aint_lower, .both);

    try writeAll(file, "#endif // !SOFTMENUCATALOGS_H\n");
}

fn emitMenu(file: *c.FILE, menu_name: []const u8, catalog_type: u16, generation_type: GenerationType) !void {
    const declaration_indent = if (generation_type == .both) "" else "  ";
    const only_eim = std.mem.eql(u8, menu_name, "FCNS_EIM");

    try writePrint(file, "{s}  TO_QSPI const int16_t menu_{s}[] = {{\n", .{ declaration_indent, menu_name });

    var item_list: [max_number_of_items]i32 = undefined;
    var number_of_items: usize = 0;
    var item_index: usize = 1;

    while (item_index < last_item) : (item_index += 1) {
        const entry = indexOfItems[item_index];
        const entry_name = cString(&entry.itemCatalogName);

        if ((entry.status & cat_status) != catalog_type) continue;
        if (std.mem.eql(u8, entry_name, "CATALOG") or std.mem.eql(u8, entry_name, "MENUS")) continue;
        if (only_eim and (entry.status & eim_status) != eim_enabled) continue;

        if (number_of_items == max_number_of_items) return error.TooManyItems;
        item_list[number_of_items] = @intCast(item_index);
        number_of_items += 1;
    }

    insertionSort(item_list[0..number_of_items]);

    if (generation_type == .pc or generation_type == .dmcp) {
        try writePrint(file, "{s}    ", .{declaration_indent});
    }

    for (item_list[0..number_of_items], 0..) |item_id, index| {
        const signed_item = if (catalog_type == cat_menu) -item_id else item_id;
        try writePaddedInt(file, signed_item, 5);
        try writeByte(file, ',');

        if ((index + 1) % 6 == 0) {
            try writeByte(file, '\n');
            if (generation_type == .pc or generation_type == .dmcp) {
                try writePrint(file, "{s}    ", .{declaration_indent});
            }
        }
    }

    if (generation_type == .pc or generation_type == .dmcp) {
        try writeAll(file, "\n    };\n");
    } else {
        try writeAll(file, "\n  };\n");
    }
}

fn insertionSort(items: []i32) void {
    var i: usize = 1;
    while (i < items.len) : (i += 1) {
        const value = items[i];
        var j = i;
        while (j > 0 and compareItemIds(value, items[j - 1]) < 0) : (j -= 1) {
            items[j] = items[j - 1];
        }
        items[j] = value;
    }
}

fn compareItemIds(left: i32, right: i32) i32 {
    const left_index: usize = @intCast(left);
    const right_index: usize = @intCast(right);
    return compareString(cStringZ(&indexOfItems[left_index].itemCatalogName), cStringZ(&indexOfItems[right_index].itemCatalogName), cmp_extensive);
}

fn cString(bytes: *const [16]u8) []const u8 {
    var len: usize = 0;
    while (len < 16 and bytes.*[len] != 0) : (len += 1) {}
    return bytes.*[0..len];
}

fn cStringZ(bytes: *const [16]u8) [*:0]const u8 {
    return @ptrCast(&bytes.*[0]);
}

fn writePaddedInt(file: *c.FILE, value: i32, width: usize) !void {
    var buffer: [32]u8 = undefined;
    const text = try std.fmt.bufPrint(&buffer, "{d}", .{value});
    const padding = if (text.len < width) width - text.len else 0;

    var count: usize = 0;
    while (count < padding) : (count += 1) {
        try writeByte(file, ' ');
    }
    try writeAll(file, text);
}

fn writePrint(file: *c.FILE, comptime fmt: []const u8, args: anytype) !void {
    var buffer: [256]u8 = undefined;
    const text = try std.fmt.bufPrint(&buffer, fmt, args);
    try writeAll(file, text);
}

fn writeByte(file: *c.FILE, byte: u8) !void {
    if (c.fwrite(&byte, 1, 1, file) != 1) return error.FileWriteFailed;
}

fn writeAll(file: *c.FILE, contents: []const u8) !void {
    if (contents.len == 0) return;
    if (c.fwrite(contents.ptr, 1, contents.len, file) != contents.len) return error.FileWriteFailed;
}
