// SPDX-License-Identifier: GPL-3.0-only
//
// Zig owner for src/c47/debug.c: the data-type / mode / curve-fit name helpers
// plus the big TO_QSPI typeName[7][11][24] byte table. getDataTypeName /
// getRegisterDataTypeName / getRegisterTagName / getRunningModeName /
// getCurveFitModeName / getCurveFitModeNames / getCurveFitModeFormula /
// getAngularModeName / getShortIntegerModeName / eatSpacesEnd / eatSpacesMid /
// LogBaseTwoOfPowersOfTwo are all faithful, line-by-line ports.
//
// Dead code skipped (matches the C preprocessor state for every z47 build):
//   - getCalcModeName is gated on DEBUG_INSTEAD_STATUS_BAR == 1, but
//     defines.h forces DEBUG_INSTEAD_STATUS_BAR == 0, so it is never compiled.
//   - debugNIM is commented out in the source.
// stackCheck / initStackCheck / stackSmashingTest are defined only under
// #if defined(PC_BUILD); they are exported host-only here (no-op on firmware,
// where the C symbols also do not exist).
//
// debug.c is not reachable from the testSuite; verification is by build/link
// across every target plus the boundary gates.

const abi = @import("abi");
const std = @import("std");
const builtin = @import("builtin");
const frontier_build_options = @import("frontier_build_options");
const dmcp_build: bool = frontier_build_options.dmcp_build;

// The TO_QSPI typeName table is pure bytes (no pointers) so it can live in the
// executable QSPI region on flash-limited old_hw DM42, matching the siblings.
const code_section = if (frontier_build_options.dmcp_build and frontier_build_options.old_hw)
    ".qspi_data"
else if (builtin.target.os.tag == .macos)
    "__TEXT,__text"
else
    ".text";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------
const bool_t = bool;
const calcRegister_t = i16;
const angularMode_t = c_int;

// ---------------------------------------------------------------------------
// Constants / enum values (verified via C probe against the sim build)
// ---------------------------------------------------------------------------
const dtLongInteger: u32 = 0;
const dtReal34: u32 = 1;
const dtComplex34: u32 = 2;
const dtTime: u32 = 3;
const dtDate: u32 = 4;
const dtString: u32 = 5;
const dtReal34Matrix: u32 = 6;
const dtComplex34Matrix: u32 = 7;
const dtShortInteger: u32 = 8;
const dtConfig: u32 = 9;

const LI_ZERO: u32 = 0;
const LI_NEGATIVE: u32 = 1;
const LI_POSITIVE: u32 = 2;

const amRadian = 0;
const amGrad = 1;
const amDegree = 2;
const amDMS = 3;
const amMultPi = 4;
const amNone = 5;
const amPolar: u32 = 16;

const SIM_UNSIGN: u32 = 0;
const SIM_1COMPL: u32 = 1;
const SIM_2COMPL: u32 = 2;
const SIM_SIGNMT: u32 = 3;

const CF_ORTHOGONAL_FITTING: u16 = 512;

// ---------------------------------------------------------------------------
// Externs (runtime symbols / other owners / libc)
// ---------------------------------------------------------------------------
extern fn getRegisterDataType(regist: calcRegister_t) u32;
extern fn getRegisterTag(regist: calcRegister_t) u32;
extern var errorMessage: [*c]u8;

extern fn strcpy(dst: [*c]u8, src: [*c]const u8) [*c]u8;
extern fn strcat(dst: [*c]u8, src: [*c]const u8) [*c]u8;
extern fn strlen(s: [*c]const u8) usize;
extern fn sprintf(buf: [*c]u8, fmt: [*:0]const u8, ...) c_int;
extern fn printf(fmt: [*:0]const u8, ...) c_int;

// ---------------------------------------------------------------------------
// Inline wrappers (the C macros)
// ---------------------------------------------------------------------------
// orOrtho(a) == (a == 0 ? CF_ORTHOGONAL_FITTING : a)
inline fn orOrtho(a: u16) u16 {
    return if (a == 0) CF_ORTHOGONAL_FITTING else a;
}
// getComplexRegisterPolarMode(reg) == (getRegisterTag(reg) & amPolar)
inline fn getComplexRegisterPolarMode(reg: calcRegister_t) u32 {
    return getRegisterTag(reg) & amPolar;
}
// stringByteLength(str) == (int32_t)strlen(str)
inline fn stringByteLength(s: [*c]const u8) i32 {
    return @intCast(strlen(s));
}

// ---------------------------------------------------------------------------
// typeName[7][11][24] (TO_QSPI const char). Generated byte-exact from the C.
// ---------------------------------------------------------------------------
pub export const typeName linksection(code_section) = [7][11][24]u8{
    .{
        .{ 63, 63, 63, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 108, 111, 110, 103, 32, 105, 110, 116, 101, 103, 101, 114, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 114, 101, 97, 108, 51, 52, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 99, 111, 109, 112, 108, 101, 120, 51, 52, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 116, 105, 109, 101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 100, 97, 116, 101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 115, 116, 114, 105, 110, 103, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 114, 101, 97, 108, 51, 52, 32, 109, 97, 116, 114, 105, 120, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 99, 111, 109, 112, 108, 101, 120, 51, 52, 32, 109, 97, 116, 114, 105, 120, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 115, 104, 111, 114, 116, 32, 105, 110, 116, 101, 103, 101, 114, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 99, 111, 110, 102, 105, 103, 32, 100, 97, 116, 97, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    },
    .{
        .{ 63, 63, 63, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0 },
        .{ 108, 111, 110, 103, 32, 105, 110, 116, 101, 103, 101, 114, 32, 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0 },
        .{ 114, 101, 97, 108, 51, 52, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0 },
        .{ 99, 111, 109, 112, 108, 101, 120, 51, 52, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0 },
        .{ 116, 105, 109, 101, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0 },
        .{ 100, 97, 116, 101, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0 },
        .{ 115, 116, 114, 105, 110, 103, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0 },
        .{ 114, 101, 97, 108, 51, 52, 32, 109, 97, 116, 114, 105, 120, 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0 },
        .{ 99, 111, 109, 112, 108, 101, 120, 51, 52, 32, 109, 97, 116, 114, 105, 120, 32, 32, 32, 32, 32, 0, 0, 0 },
        .{ 115, 104, 111, 114, 116, 32, 105, 110, 116, 101, 103, 101, 114, 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0 },
        .{ 99, 111, 110, 102, 105, 103, 32, 100, 97, 116, 97, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0 },
    },
    .{
        .{ 97, 32, 63, 63, 63, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 97, 32, 108, 111, 110, 103, 32, 105, 110, 116, 101, 103, 101, 114, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 97, 32, 114, 101, 97, 108, 51, 52, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 97, 32, 99, 111, 109, 112, 108, 101, 120, 51, 52, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 97, 32, 116, 105, 109, 101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 97, 32, 100, 97, 116, 101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 97, 32, 115, 116, 114, 105, 110, 103, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 97, 32, 114, 101, 97, 108, 51, 52, 32, 109, 97, 116, 114, 105, 120, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 97, 32, 99, 111, 109, 112, 108, 101, 120, 51, 52, 32, 109, 97, 116, 114, 105, 120, 0, 0, 0, 0, 0, 0 },
        .{ 97, 32, 115, 104, 111, 114, 116, 32, 105, 110, 116, 101, 103, 101, 114, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 97, 32, 99, 111, 110, 102, 105, 103, 32, 100, 97, 116, 97, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    },
    .{
        .{ 97, 32, 63, 63, 63, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0 },
        .{ 97, 32, 108, 111, 110, 103, 32, 105, 110, 116, 101, 103, 101, 114, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0 },
        .{ 97, 32, 114, 101, 97, 108, 51, 52, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0 },
        .{ 97, 32, 99, 111, 109, 112, 108, 101, 120, 51, 52, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0 },
        .{ 97, 32, 116, 105, 109, 101, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0 },
        .{ 97, 32, 100, 97, 116, 101, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0 },
        .{ 97, 32, 115, 116, 114, 105, 110, 103, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0 },
        .{ 97, 32, 114, 101, 97, 108, 51, 52, 32, 109, 97, 116, 114, 105, 120, 32, 32, 32, 32, 32, 32, 0, 0, 0 },
        .{ 97, 32, 99, 111, 109, 112, 108, 101, 120, 51, 52, 32, 109, 97, 116, 114, 105, 120, 32, 32, 32, 0, 0, 0 },
        .{ 97, 32, 115, 104, 111, 114, 116, 32, 105, 110, 116, 101, 103, 101, 114, 32, 32, 32, 32, 32, 32, 0, 0, 0 },
        .{ 97, 32, 99, 111, 110, 102, 105, 103, 32, 100, 97, 116, 97, 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0 },
    },
    .{
        .{ 76, 105, 110, 101, 97, 114, 32, 32, 32, 32, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 69, 120, 112, 111, 110, 101, 110, 116, 105, 97, 108, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 76, 111, 103, 97, 114, 105, 116, 104, 109, 105, 99, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 80, 111, 119, 101, 114, 32, 32, 32, 32, 32, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 82, 111, 111, 116, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 72, 121, 112, 101, 114, 98, 111, 108, 105, 99, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 80, 97, 114, 97, 98, 111, 108, 105, 99, 32, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 67, 97, 117, 99, 104, 121, 32, 112, 101, 97, 107, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 71, 97, 117, 115, 115, 32, 112, 101, 97, 107, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 79, 114, 116, 104, 111, 103, 111, 110, 97, 108, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 63, 63, 63, 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    },
    .{
        .{ 97, 160, 128, 160, 4, 43, 160, 4, 97, 160, 129, 120, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 97, 160, 128, 160, 4, 101, 94, 40, 97, 160, 129, 120, 41, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 97, 160, 128, 160, 4, 43, 160, 4, 97, 160, 129, 108, 110, 40, 120, 41, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 97, 160, 128, 160, 4, 120, 94, 97, 160, 129, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 97, 160, 128, 160, 4, 97, 160, 129, 94, 40, 49, 47, 120, 41, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 40, 97, 160, 128, 160, 4, 43, 160, 4, 97, 160, 129, 120, 41, 161, 107, 161, 97, 0, 0, 0, 0, 0, 0 },
        .{ 97, 160, 128, 160, 4, 43, 160, 4, 97, 160, 129, 120, 160, 4, 43, 160, 4, 97, 160, 130, 120, 161, 98, 0 },
        .{ 91, 97, 160, 128, 40, 120, 43, 97, 160, 129, 41, 161, 98, 43, 97, 160, 130, 93, 161, 107, 161, 97, 0, 0 },
        .{ 97, 160, 128, 101, 94, 91, 40, 120, 45, 97, 160, 129, 41, 161, 98, 47, 97, 160, 130, 93, 0, 0, 0, 0 },
        .{ 97, 160, 128, 160, 4, 43, 160, 4, 97, 160, 129, 120, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 63, 63, 63, 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    },
    .{
        .{ 80, 71, 77, 95, 83, 84, 79, 80, 80, 69, 68, 32, 32, 32, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 80, 71, 77, 95, 82, 85, 78, 78, 73, 78, 71, 32, 32, 32, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 80, 71, 77, 95, 87, 65, 73, 84, 73, 78, 71, 32, 32, 32, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 80, 71, 77, 95, 80, 65, 85, 83, 69, 68, 32, 32, 32, 32, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 80, 71, 77, 95, 75, 69, 89, 46, 46, 80, 65, 85, 83, 69, 68, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 80, 71, 77, 95, 82, 69, 83, 85, 77, 73, 78, 71, 32, 32, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 80, 71, 77, 95, 83, 73, 78, 71, 76, 69, 95, 83, 84, 69, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 80, 71, 77, 95, 85, 78, 68, 69, 70, 73, 78, 69, 68, 32, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 63, 63, 63, 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 63, 63, 63, 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
        .{ 63, 63, 63, 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    },
};

// ---------------------------------------------------------------------------
// getDataTypeName
// ---------------------------------------------------------------------------
fn dataTypeNameKnown(dt: u32) bool {
    return switch (dt) {
        dtLongInteger, dtTime, dtDate, dtString, dtReal34Matrix, dtComplex34Matrix, dtShortInteger, dtReal34, dtComplex34, dtConfig => true,
        else => false,
    };
}

pub export fn getDataTypeName(dt: u16, article: bool_t, padWithBlanks: bool_t) [*c]const u8 {
    if (article and padWithBlanks) {
        if (dataTypeNameKnown(dt)) {
            return &typeName[3][dt + 1];
        } else {
            return &typeName[3][0];
        }
    } else if (article and !padWithBlanks) {
        if (dataTypeNameKnown(dt)) {
            return &typeName[2][dt + 1];
        } else {
            return &typeName[2][0];
        }
    } else if (!article and padWithBlanks) {
        if (dataTypeNameKnown(dt)) {
            return &typeName[1][dt + 1];
        } else {
            return &typeName[1][0];
        }
    } else if (!article and !padWithBlanks) {
        if (dataTypeNameKnown(dt)) {
            return &typeName[0][dt + 1];
        } else {
            return &typeName[0][0];
        }
    } else {
        return &typeName[0][0];
    }
}

// ---------------------------------------------------------------------------
// getRegisterDataTypeName
// ---------------------------------------------------------------------------
pub export fn getRegisterDataTypeName(regist: calcRegister_t, article: bool_t, padWithBlanks: bool_t) [*c]const u8 {
    return getDataTypeName(@truncate(getRegisterDataType(regist)), article, padWithBlanks);
}

// ---------------------------------------------------------------------------
// getRegisterTagName
// ---------------------------------------------------------------------------
var getRegisterTagName_base: [9]u8 = undefined;
pub export fn getRegisterTagName(regist: calcRegister_t, padWithBlanks: bool_t) [*c]const u8 {
    _ = padWithBlanks;
    switch (getRegisterDataType(regist)) {
        dtLongInteger => {
            switch (getRegisterTag(regist)) {
                LI_ZERO => return "zero    ",
                LI_NEGATIVE => return "negative",
                LI_POSITIVE => return "positive",
                else => return "???     ",
            }
        },
        dtReal34 => {
            switch (getRegisterTag(regist)) {
                amRadian => return "radian  ",
                amMultPi => return "multPi  ",
                amGrad => return "grad    ",
                amDegree => return "degree  ",
                amDMS => return "dms     ",
                amNone => return "none    ",
                else => return "???     ",
            }
        },
        dtComplex34 => {
            if (getComplexRegisterPolarMode(regist) != 0) {
                return "Polar   ";
            } else {
                return "Rect    ";
            }
        },
        dtString, dtReal34Matrix, dtComplex34Matrix, dtDate, dtTime, dtConfig => {
            switch (getRegisterTag(regist)) {
                amNone => return "        ",
                else => return "???     ",
            }
        },
        dtShortInteger => {
            abi.fmtBufZ(&getRegisterTagName_base, "base {d: >2} ", .{@as(u32, getRegisterTag(regist))});
            return &getRegisterTagName_base;
        },
        else => {
            return "???     ";
        },
    }
}

// ---------------------------------------------------------------------------
// LogBaseTwoOfPowersOfTwo
// ---------------------------------------------------------------------------
pub export fn LogBaseTwoOfPowersOfTwo(selection: u16) u16 {
    var jj: u16 = orOrtho(selection) & 0x03FF;
    jj = jj ^ (jj & (jj -% 1));
    var r: u16 = @intFromBool((jj & 0xAAAA) != 0);
    r |= @as(u16, @intFromBool((jj & 0xFF00) != 0)) << 3;
    r |= @as(u16, @intFromBool((jj & 0xF0F0) != 0)) << 2;
    r |= @as(u16, @intFromBool((jj & 0xCCCC) != 0)) << 1;
    return r;
}

// ---------------------------------------------------------------------------
// getRunningModeName
// ---------------------------------------------------------------------------
pub export fn getRunningModeName(mode: u16) [*c]const u8 {
    return &typeName[6][mode];
}

// ---------------------------------------------------------------------------
// getCurveFitModeName
// ---------------------------------------------------------------------------
pub export fn getCurveFitModeName(selection: u16) [*c]const u8 {
    return &typeName[4][LogBaseTwoOfPowersOfTwo(selection)];
}

// ---------------------------------------------------------------------------
// eatSpacesEnd (file-scope static tmp_names[20])
// ---------------------------------------------------------------------------
var eatSpacesEnd_tmp_names: [20]u8 = undefined;
pub export fn eatSpacesEnd(ss: [*c]const u8) [*c]u8 {
    _ = strcpy(&eatSpacesEnd_tmp_names, ss);
    var ix: i8 = @truncate(stringByteLength(ss) - 1);
    while (ix > 0) {
        if (ss[@intCast(ix)] == ' ') {
            eatSpacesEnd_tmp_names[@intCast(ix)] = 0;
        } else {
            break;
        }
        ix -= 1;
    }
    return &eatSpacesEnd_tmp_names;
}

// ---------------------------------------------------------------------------
// eatSpacesMid (file-scope static tmp_names[20])
// ---------------------------------------------------------------------------
var eatSpacesMid_tmp_names: [20]u8 = undefined;
pub export fn eatSpacesMid(ss: [*c]const u8) [*c]u8 {
    var tt: [50]u8 = undefined;
    var ix: i8 = 0;
    var iy: i8 = 0;

    _ = strcpy(&tt, ss);
    eatSpacesMid_tmp_names[0] = 0;
    while (tt[@intCast(ix)] != 0 and ix < 50) {
        if (tt[@intCast(ix)] != ' ') {
            eatSpacesMid_tmp_names[@intCast(iy)] = tt[@intCast(ix)];
            iy += 1;
        }
        ix += 1;
    }
    eatSpacesMid_tmp_names[@intCast(iy)] = 0;
    eatSpacesMid_tmp_names[@intCast(iy)] = 0;
    iy += 1;
    return &eatSpacesMid_tmp_names;
}

// ---------------------------------------------------------------------------
// getCurveFitModeNames. The PC_BUILD body builds errorMessage; on firmware the
// C returns the empty string.
// ---------------------------------------------------------------------------
pub export fn getCurveFitModeNames(selection: u16) [*c]const u8 {
    if (comptime !dmcp_build) {
        errorMessage[0] = 0;
        var ix: u16 = 0;
        while (ix < 10) : (ix += 1) {
            if ((selection & (@as(u16, 1) << @intCast(ix))) != 0) {
                _ = strcat(errorMessage, if (errorMessage[0] == 0) "" else " ");
                _ = strcat(errorMessage, eatSpacesEnd(getCurveFitModeName(@as(u16, 1) << @intCast(ix))));
            }
        }
        if (errorMessage[0] == 0) {
            return "???        ";
        }
        return errorMessage;
    } else {
        return "";
    }
}

// ---------------------------------------------------------------------------
// getCurveFitModeFormula
// ---------------------------------------------------------------------------
pub export fn getCurveFitModeFormula(selection: u16) [*c]const u8 {
    return &typeName[5][LogBaseTwoOfPowersOfTwo(orOrtho(selection) & 0x03FF)];
}

// ---------------------------------------------------------------------------
// getAngularModeName
// ---------------------------------------------------------------------------
pub export fn getAngularModeName(angularMode: angularMode_t) [*c]const u8 {
    switch (angularMode) {
        amRadian => return "radian",
        amMultPi => return "multPi",
        amGrad => return "grad  ",
        amDegree => return "degree",
        amDMS => return "d.ms  ",
        amNone => return "none  ",
        else => return "???   ",
    }
}

// ---------------------------------------------------------------------------
// getShortIntegerModeName
// ---------------------------------------------------------------------------
pub export fn getShortIntegerModeName(im: u16) [*c]const u8 {
    switch (im) {
        SIM_1COMPL => return "1compl",
        SIM_2COMPL => return "2compl",
        SIM_SIGNMT => return "signmt",
        SIM_UNSIGN => return "unsign",
        else => return "???   ",
    }
}

// ---------------------------------------------------------------------------
// PC_BUILD-only stack-smashing detectors (host-only; the C symbols do not
// exist on firmware).
// ---------------------------------------------------------------------------
fn stackCheckImpl(begin: [*c]const u8, end: [*c]const u8, size: c_int, where: [*c]const u8) callconv(.c) void {
    var corrupted: c_int = 0;
    var i: c_int = 0;
    while (i < size) : (i += 1) {
        if (begin[@intCast(i)] != 0xaa) {
            _ = printf("Stack begin corrupted: begin[%d]=0x%02x at %s\n", i, @as(c_uint, begin[@intCast(i)]), where);
            corrupted = 1;
        }
    }
    i = 0;
    while (i < size) : (i += 1) {
        if (end[@intCast(i)] != 0xaa) {
            _ = printf("Stack end corrupted: end[%d]=0x%02x at %s\n", i, @as(c_uint, end[@intCast(i)]), where);
            corrupted = 1;
        }
    }
    if (corrupted != 0) {
        exit(0xBAD);
    }
}

fn initStackCheckImpl(begin: [*c]u8, end: [*c]u8, size: c_int) callconv(.c) void {
    _ = memset(begin, 0xaa, @intCast(size));
    _ = memset(end, 0xaa, @intCast(size));
}

fn stackSmashingTestImpl() callconv(.c) void {
    var stackEnd: [10000]u8 = undefined; // First declaration
    var v1: c_int = undefined;
    var v2: c_int = undefined;
    var v3: c_int = undefined;
    var stackBegin: [10000]u8 = undefined; // Last declaration

    initStackCheckImpl(&stackBegin, &stackEnd, 10000);

    v1 = 1;
    stackCheckImpl(&stackBegin, &stackEnd, 10000, "after v1 = ...");
    v2 = v1 + 1;
    stackCheckImpl(&stackBegin, &stackEnd, 10000, "after v2 = ...");
    v3 = v2 + 2;
    stackCheckImpl(&stackBegin, &stackEnd, 10000, "after v3 = ...");
    _ = printf("v1=%d v2=%d v3=%d\n", v1, v2, v3);
    stackCheckImpl(&stackBegin, &stackEnd, 10000, "after printf(...");
}

extern fn exit(status: c_int) noreturn;
extern fn memset(dst: [*c]u8, val: c_int, n: usize) [*c]u8;

comptime {
    if (!dmcp_build) {
        @export(&stackCheckImpl, .{ .name = "stackCheck", .linkage = .strong });
        @export(&initStackCheckImpl, .{ .name = "initStackCheck", .linkage = .strong });
        @export(&stackSmashingTestImpl, .{ .name = "stackSmashingTest", .linkage = .strong });
    }
}
