pub extern fn z47_frontier_retained_fnSNAP(unused_but_mandatory_parameter: u16) void;
pub extern fn z47_frontier_retained_fnDynamicMenu(unused_but_mandatory_parameter: u16) void;
pub extern fn z47_frontier_retained_fnNop(unused_but_mandatory_parameter: u16) void;
pub extern fn z47_frontier_retained_fnCFGsettings(unused_but_mandatory_parameter: u16) void;
pub extern fn z47_frontier_retained_fnP_PrinterOnOff(op: u16) void;
pub extern fn z47_frontier_retained_fnKeysManagement(choice: u16) void;
pub extern fn z47_frontier_retained_fnPlotStat(plot_mode: u16) void;
pub extern fn z47_frontier_retained_fnEditMatrix(regist: u16) void;
pub extern fn z47_frontier_retained_fnClPAll(confirmation: u16) void;