const std = @import("std");
const build_common = @import("../common.zig");
const host_platform = @import("platform.zig");
const host_types = @import("types.zig");

pub fn addVersionHeaders(b: *std.Build, ci_commit_tag: []const u8) !std.Build.LazyPath {
    const vcs_tag = build_common.commandOutput(b, &.{ "git", "describe", "--match=NeVeRmAtCh", "--always", "--abbrev=8", "--dirty=-mod" }) orelse "unknown";
    const today = build_common.commandOutput(b, &.{ "date", "+%Y-%m-%d" }) orelse "1970-01-01";

    const vcs_content = try std.fmt.allocPrint(b.allocator,
        \\// SPDX-License-Identifier: GPL-3.0-only
        \\// SPDX-FileCopyrightText: Copyright The WP43 and C47 Authors
        \\
        \\/********************************************//**
        \\* \\file vcs.h
        \\***********************************************/
        \\
        \\/***********************************************************************************
        \\* Do not edit this file manually! It's automagically generated by the build system *
        \\************************************************************************************/
        \\
        \\#if !defined(VCS_H)
        \\  #define VCS_H
        \\
        \\  #define VCS_COMMIT_ID  "{s}"
        \\#endif // !VCS_H
        \\
    , .{vcs_tag});

    const version_content = if (ci_commit_tag.len > 0)
        try std.fmt.allocPrint(b.allocator,
            \\// SPDX-License-Identifier: GPL-3.0-only
            \\// SPDX-FileCopyrightText: Copyright The WP43 and C47 Authors
            \\
            \\/********************************************//**
            \\* \\file version.h
            \\***********************************************/
            \\
            \\/***********************************************************************************
            \\* Do not edit this file manually! It's automagically generated by the build system *
            \\************************************************************************************/
            \\
            \\#if !defined(VERSION_H)
            \\  #define VERSION_H
            \\
            \\  #define VERSION_STRING "v{s}" STD_SPACE_3_PER_EM "{s}"
            \\  #define VERSION_SHORT  "{s}"
            \\  #define VERSION_WINRS    0,0,0,0
            \\  #define VERSION_MODDED   0
            \\
            \\#endif // !VERSION_H
            \\
        , .{ ci_commit_tag, today, ci_commit_tag })
    else
        try std.fmt.allocPrint(b.allocator,
            \\// SPDX-License-Identifier: GPL-3.0-only
            \\// SPDX-FileCopyrightText: Copyright The WP43 and C47 Authors
            \\
            \\/********************************************//**
            \\* \\file version.h
            \\***********************************************/
            \\
            \\/***********************************************************************************
            \\* Do not edit this file manually! It's automagically generated by the build system *
            \\************************************************************************************/
            \\
            \\#if !defined(VERSION_H)
            \\  #define VERSION_H
            \\
            \\  #include "vcs.h"
            \\  #define VERSION_STRING "custom" STD_SPACE_3_PER_EM "build" STD_SPACE_3_PER_EM VCS_COMMIT_ID STD_SPACE_3_PER_EM "{s}"
            \\  #define VERSION_SHORT  VCS_COMMIT_ID
            \\  #define VERSION_WINRS    0,0,0,0
            \\  #define VERSION_MODDED   0
            \\
            \\#endif // !VERSION_H
            \\
        , .{today});

    const write_files = b.addWriteFiles();
    _ = write_files.add("vcs.h", vcs_content);
    _ = write_files.add("version.h", version_content);
    return write_files.getDirectory();
}

pub fn addGeneratorSteps(
    b: *std.Build,
    host_target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    common: host_types.CommonConfig,
) !host_types.GeneratedOutputs {
    const core_c_flags = if (host_target.result.os.tag == .windows)
        build_common.common_c_flags_windows
    else
        build_common.common_c_flags;

    const raster_fonts_gen = b.addExecutable(.{
        .name = "ttf2RasterFonts",
        .root_module = b.createModule(.{
            .root_source_file = null,
            .target = host_target,
            .optimize = optimize,
            .link_libc = true,
        }),
    });
    host_platform.addHostMacros(raster_fonts_gen.root_module, common);
    host_platform.addHostSystemPaths(raster_fonts_gen.root_module, common);
    raster_fonts_gen.root_module.addCSourceFile(.{ .file = b.path("src/ttf2RasterFonts/ttf2RasterFonts.c"), .flags = build_common.font_generator_c_flags });
    host_platform.linkRasterFontsFreetype(raster_fonts_gen.root_module, common);

    const run_raster_fonts = b.addRunArtifact(raster_fonts_gen);
    run_raster_fonts.setCwd(b.path("."));
    run_raster_fonts.addArg("res/fonts");
    const raster_fonts_data = run_raster_fonts.addOutputFileArg("rasterFontsData.c");

    const generate_constants = b.addExecutable(.{
        .name = "generateConstants",
        .root_module = b.createModule(.{
            .root_source_file = null,
            .target = host_target,
            .optimize = optimize,
            .link_libc = true,
        }),
    });
    host_platform.addHostMacros(generate_constants.root_module, common);
    host_platform.addHostSystemPaths(generate_constants.root_module, common);
    generate_constants.root_module.addCMacro("GENERATE_CONSTANTS", "1");
    generate_constants.root_module.addIncludePath(b.path("dep/decNumberICU"));
    generate_constants.root_module.addIncludePath(b.path("src/c47"));
    generate_constants.root_module.addCSourceFiles(.{ .root = b.path("dep"), .files = build_common.decnumber_sources, .flags = core_c_flags });
    generate_constants.root_module.addCSourceFile(.{ .file = b.path("src/generateConstants/generateConstants.c"), .flags = build_common.generate_constants_c_flags });
    host_platform.linkGtk3(generate_constants.root_module, common);

    const run_generate_constants = b.addRunArtifact(generate_constants);
    run_generate_constants.setCwd(b.path("."));
    const constant_pointers_c = run_generate_constants.addOutputFileArg("constantPointers.c");
    const constant_pointers_h = run_generate_constants.addOutputFileArg("constantPointers.h");
    const constant_pointers2_c = run_generate_constants.addOutputFileArg("constantPointers2.c");

    const generate_catalogs = b.addExecutable(.{
        .name = "generateCatalogs",
        .root_module = b.createModule(.{
            .root_source_file = null,
            .target = host_target,
            .optimize = optimize,
            .link_libc = true,
        }),
    });
    host_platform.addHostMacros(generate_catalogs.root_module, common);
    host_platform.addHostSystemPaths(generate_catalogs.root_module, common);
    generate_catalogs.root_module.addCMacro("GENERATE_CATALOGS", "1");
    generate_catalogs.root_module.addIncludePath(b.path("dep/decNumberICU"));
    generate_catalogs.root_module.addIncludePath(b.path("src/c47"));
    generate_catalogs.root_module.addCSourceFiles(.{ .root = b.path("dep"), .files = build_common.decnumber_sources, .flags = core_c_flags });
    generate_catalogs.root_module.addCSourceFiles(.{ .root = b.path("src/c47"), .files = build_common.generate_catalogs_sources, .flags = core_c_flags });
    generate_catalogs.root_module.addCSourceFile(.{ .file = b.path("src/generateCatalogs/generateCatalogs.c"), .flags = build_common.generate_catalogs_c_flags });
    generate_catalogs.root_module.addCSourceFile(.{ .file = raster_fonts_data, .flags = core_c_flags });
    host_platform.linkGtk3(generate_catalogs.root_module, common);
    generate_catalogs.root_module.linkSystemLibrary("gmp", .{ .use_pkg_config = .yes });

    const run_generate_catalogs = b.addRunArtifact(generate_catalogs);
    run_generate_catalogs.setCwd(b.path("."));
    const softmenu_catalogs = run_generate_catalogs.addOutputFileArg("softmenuCatalogs.h");

    const generate_testpgms = b.addExecutable(.{
        .name = "generateTestPgms",
        .root_module = b.createModule(.{
            .root_source_file = null,
            .target = host_target,
            .optimize = optimize,
            .link_libc = true,
        }),
    });
    host_platform.addHostMacros(generate_testpgms.root_module, common);
    host_platform.addHostSystemPaths(generate_testpgms.root_module, common);
    generate_testpgms.root_module.addCMacro("GENERATE_TESTPGMS", "1");
    generate_testpgms.root_module.addIncludePath(b.path("dep/decNumberICU"));
    generate_testpgms.root_module.addIncludePath(b.path("src/c47"));
    generate_testpgms.root_module.addCSourceFiles(.{ .root = b.path("dep"), .files = build_common.decnumber_sources, .flags = core_c_flags });
    generate_testpgms.root_module.addCSourceFiles(.{ .root = b.path("src/c47"), .files = build_common.generate_testpgms_sources, .flags = core_c_flags });
    generate_testpgms.root_module.addCSourceFile(.{ .file = b.path("src/generateTestPgms/generateTestPgms.c"), .flags = build_common.generate_testpgms_c_flags });
    host_platform.linkGtk3(generate_testpgms.root_module, common);
    generate_testpgms.root_module.linkSystemLibrary("gmp", .{ .use_pkg_config = .yes });

    const run_generate_testpgms = b.addRunArtifact(generate_testpgms);
    run_generate_testpgms.setCwd(b.path("."));
    const test_pgms_bin = run_generate_testpgms.addOutputFileArg("testPgms.bin");

    return .{
        .raster_fonts_data = raster_fonts_data,
        .softmenu_catalogs = softmenu_catalogs,
        .constant_pointers_c = constant_pointers_c,
        .constant_pointers_h = constant_pointers_h,
        .constant_pointers2_c = constant_pointers2_c,
        .test_pgms_bin = test_pgms_bin,
    };
}