// Owner module for setupUI (ported from src/c47-gtk/gtkGui.c). Host-sim only
// (PC_BUILD / SIMULATOR_ON_SCREEN_KEYBOARD == 1). Builds the GTK on-screen
// keyboard: creates the ~260 button/label widgets, sets their tooltips/sizes/
// signal handlers and lays them out with gtk_fixed. The widget globals remain
// C-defined in gtkGui.c; this Zig code assigns them through extern var.
// check_all_btn_widgets_for_consistency stays in C and is called via extern.

const CSSFILE = "res/c47_pre.css";
const SCREEN_WIDTH = 400;
const SCREEN_HEIGHT = 240;
const GTK_STYLE_PROVIDER_PRIORITY_USER: c_uint = 800;

// Keyboard-layout geometry (defines.h, SIMULATOR_ON_SCREEN_KEYBOARD lane).
const KEY_WIDTH_1: c_int = 47;
const KEY_WIDTH_2: c_int = 56;
const DELTA_KEYS_X: c_int = 78;
const DELTA_KEYS_Y: c_int = 74;
const X_LEFT_PORTRAIT: c_int = 45;
const X_LEFT_LANDSCAPE: c_int = 544;
const Y_TOP_PORTRAIT: c_int = 376;
const Y_TOP_LANDSCAPE: c_int = 30;
const X_OFFSET_LETTER: c_int = 3;
const Y_OFFSET_LETTER: c_int = 18;
const LARGE_KEY_SPACING_1: c_int = 18;
const LARGE_KEY_SPACING_2: c_int = 17;

const USER_R47f_g = 61;
const USER_R47bk_fg = 62;
const USER_R47fg_bk = 63;
const USER_R47fg_g = 64;

const shortCut_t = extern struct {
    C47: [16]u8,
    C47A: [16]u8,
    R47: [16]u8,
    R47A: [16]u8,
};

extern var grid: ?*anyopaque;
extern var frmCalc: ?*anyopaque;
extern var cssData: [*c]u8;
extern var lcd_buffer: [*c]u8;
extern var calcLandscape: bool;
extern var enableFunctionKeysDisplay: bool;
extern var calcModel: u8;

fn s16(comptime str: []const u8) [16]u8 {
    var a = [_]u8{0} ** 16;
    @memcpy(a[0..str.len], str);
    return a;
}

// Per-key shortcut tooltip strings (ported from gtkGui.c). Indexed by
// keyCnt/keyCntA in setupUI; the C/R variants pick the C47-family vs R47-family
// tooltip and the A variants are the alpha-mode labels.
// zig fmt: off
const shortCutString = [_]shortCut_t{
    .{ .C47 = s16("a"), .C47A = s16("A"), .R47 = s16("Q"), .R47A = s16("A") },
    .{ .C47 = s16("v"), .C47A = s16("B"), .R47 = s16("q"), .R47A = s16("B") },
    .{ .C47 = s16("q"), .C47A = s16("C"), .R47 = s16("v"), .R47A = s16("C") },
    .{ .C47 = s16("o"), .C47A = s16("D"), .R47 = s16("Y"), .R47A = s16("D") },
    .{ .C47 = s16("l"), .C47A = s16("E"), .R47 = s16("o"), .R47A = s16("E") },
    .{ .C47 = s16("x"), .C47A = s16("F"), .R47 = s16("l"), .R47A = s16("F") },
    .{ .C47 = s16("m"), .C47A = s16("G"), .R47 = s16("m"), .R47A = s16("G") },
    .{ .C47 = s16("r"), .C47A = s16("H"), .R47 = s16("r"), .R47A = s16("H") },
    .{ .C47 = s16("d"), .C47A = s16("I"), .R47 = s16("d"), .R47A = s16("I") },
    .{ .C47 = s16("s"), .C47A = s16("J"), .R47 = s16(">"), .R47A = s16("J") },
    .{ .C47 = s16("c"), .C47A = s16("K"), .R47 = s16(""), .R47A = s16("") },
    .{ .C47 = s16("t"), .C47A = s16("L"), .R47 = s16(""), .R47A = s16("") },
    .{ .C47 = s16("Enter"), .C47A = s16(""), .R47 = s16("Enter"), .R47A = s16("") },
    .{ .C47 = s16("w"), .C47A = s16("M"), .R47 = s16("w"), .R47A = s16("K") },
    .{ .C47 = s16("n"), .C47A = s16("N"), .R47 = s16("n"), .R47A = s16("L") },
    .{ .C47 = s16("e"), .C47A = s16("O"), .R47 = s16("e"), .R47A = s16("M") },
    .{ .C47 = s16("Backspace"), .C47A = s16(""), .R47 = s16("Backspace"), .R47A = s16("") },
    .{ .C47 = s16("Up"), .C47A = s16(""), .R47 = s16("x"), .R47A = s16("") },
    .{ .C47 = s16("7"), .C47A = s16("P"), .R47 = s16("7"), .R47A = s16("N") },
    .{ .C47 = s16("8"), .C47A = s16("Q"), .R47 = s16("8"), .R47A = s16("O") },
    .{ .C47 = s16("9"), .C47A = s16("R"), .R47 = s16("9"), .R47A = s16("P") },
    .{ .C47 = s16("/"), .C47A = s16("S"), .R47 = s16("/"), .R47A = s16("Q") },
    .{ .C47 = s16("Dn"), .C47A = s16(""), .R47 = s16("Up"), .R47A = s16("") },
    .{ .C47 = s16("4"), .C47A = s16("T"), .R47 = s16("4"), .R47A = s16("R") },
    .{ .C47 = s16("5"), .C47A = s16("U"), .R47 = s16("5"), .R47A = s16("S") },
    .{ .C47 = s16("6"), .C47A = s16("V"), .R47 = s16("6"), .R47A = s16("T") },
    .{ .C47 = s16("x"), .C47A = s16("W"), .R47 = s16("x"), .R47A = s16("U") },
    .{ .C47 = s16("f/g"), .C47A = s16(""), .R47 = s16("Dn"), .R47A = s16("") },
    .{ .C47 = s16("1"), .C47A = s16("X"), .R47 = s16("1"), .R47A = s16("V") },
    .{ .C47 = s16("2"), .C47A = s16("Y"), .R47 = s16("2"), .R47A = s16("W") },
    .{ .C47 = s16("3"), .C47A = s16("Z"), .R47 = s16("3"), .R47A = s16("X") },
    .{ .C47 = s16("-"), .C47A = s16("_"), .R47 = s16("-"), .R47A = s16("Y") },
    .{ .C47 = s16("Esc"), .C47A = s16(""), .R47 = s16("Esc"), .R47A = s16("") },
    .{ .C47 = s16("0"), .C47A = s16(":"), .R47 = s16("0"), .R47A = s16("Z") },
    .{ .C47 = s16("."), .C47A = s16("."), .R47 = s16("."), .R47A = s16(",") },
    .{ .C47 = s16("\\"), .C47A = s16("?"), .R47 = s16("\\"), .R47A = s16("?") },
    .{ .C47 = s16("+"), .C47A = s16("Space"), .R47 = s16("+"), .R47A = s16("Space") },
};
// zig fmt: on

extern var btn11: ?*anyopaque;
extern var btn12: ?*anyopaque;
extern var btn13: ?*anyopaque;
extern var btn14: ?*anyopaque;
extern var btn15: ?*anyopaque;
extern var btn16: ?*anyopaque;
extern var btn21: ?*anyopaque;
extern var btn21A: ?*anyopaque;
extern var btn22: ?*anyopaque;
extern var btn22A: ?*anyopaque;
extern var btn23: ?*anyopaque;
extern var btn23A: ?*anyopaque;
extern var btn24: ?*anyopaque;
extern var btn24A: ?*anyopaque;
extern var btn25: ?*anyopaque;
extern var btn25A: ?*anyopaque;
extern var btn26: ?*anyopaque;
extern var btn26A: ?*anyopaque;
extern var btn31: ?*anyopaque;
extern var btn31A: ?*anyopaque;
extern var btn32: ?*anyopaque;
extern var btn32A: ?*anyopaque;
extern var btn33: ?*anyopaque;
extern var btn33A: ?*anyopaque;
extern var btn34: ?*anyopaque;
extern var btn34A: ?*anyopaque;
extern var btn35: ?*anyopaque;
extern var btn35A: ?*anyopaque;
extern var btn36: ?*anyopaque;
extern var btn36A: ?*anyopaque;
extern var btn41: ?*anyopaque;
extern var btn42: ?*anyopaque;
extern var btn42A: ?*anyopaque;
extern var btn43: ?*anyopaque;
extern var btn43A: ?*anyopaque;
extern var btn44: ?*anyopaque;
extern var btn44A: ?*anyopaque;
extern var btn45: ?*anyopaque;
extern var btn51: ?*anyopaque;
extern var btn52: ?*anyopaque;
extern var btn52A: ?*anyopaque;
extern var btn53: ?*anyopaque;
extern var btn53A: ?*anyopaque;
extern var btn54: ?*anyopaque;
extern var btn54A: ?*anyopaque;
extern var btn55: ?*anyopaque;
extern var btn55A: ?*anyopaque;
extern var btn61: ?*anyopaque;
extern var btn62: ?*anyopaque;
extern var btn62A: ?*anyopaque;
extern var btn63: ?*anyopaque;
extern var btn63A: ?*anyopaque;
extern var btn64: ?*anyopaque;
extern var btn64A: ?*anyopaque;
extern var btn65: ?*anyopaque;
extern var btn65A: ?*anyopaque;
extern var btn71: ?*anyopaque;
extern var btn71A: ?*anyopaque;
extern var btn72: ?*anyopaque;
extern var btn72A: ?*anyopaque;
extern var btn73: ?*anyopaque;
extern var btn73A: ?*anyopaque;
extern var btn74: ?*anyopaque;
extern var btn74A: ?*anyopaque;
extern var btn75: ?*anyopaque;
extern var btn75A: ?*anyopaque;
extern var btn81: ?*anyopaque;
extern var btn82: ?*anyopaque;
extern var btn82A: ?*anyopaque;
extern var btn83: ?*anyopaque;
extern var btn83A: ?*anyopaque;
extern var btn84: ?*anyopaque;
extern var btn84A: ?*anyopaque;
extern var btn85: ?*anyopaque;
extern var btn85A: ?*anyopaque;
extern var lbl21F: ?*anyopaque;
extern var lbl21Fa: ?*anyopaque;
extern var lbl21G: ?*anyopaque;
extern var lbl21Gr: ?*anyopaque;
extern var lbl21L: ?*anyopaque;
extern var lbl22F: ?*anyopaque;
extern var lbl22Fa: ?*anyopaque;
extern var lbl22G: ?*anyopaque;
extern var lbl22Gr: ?*anyopaque;
extern var lbl22L: ?*anyopaque;
extern var lbl23F: ?*anyopaque;
extern var lbl23Fa: ?*anyopaque;
extern var lbl23G: ?*anyopaque;
extern var lbl23Gr: ?*anyopaque;
extern var lbl23L: ?*anyopaque;
extern var lbl24F: ?*anyopaque;
extern var lbl24Fa: ?*anyopaque;
extern var lbl24G: ?*anyopaque;
extern var lbl24Gr: ?*anyopaque;
extern var lbl24L: ?*anyopaque;
extern var lbl25F: ?*anyopaque;
extern var lbl25Fa: ?*anyopaque;
extern var lbl25G: ?*anyopaque;
extern var lbl25Gr: ?*anyopaque;
extern var lbl25L: ?*anyopaque;
extern var lbl26F: ?*anyopaque;
extern var lbl26Fa: ?*anyopaque;
extern var lbl26G: ?*anyopaque;
extern var lbl26Gr: ?*anyopaque;
extern var lbl26L: ?*anyopaque;
extern var lbl31F: ?*anyopaque;
extern var lbl31Fa: ?*anyopaque;
extern var lbl31G: ?*anyopaque;
extern var lbl31Gr: ?*anyopaque;
extern var lbl31L: ?*anyopaque;
extern var lbl32F: ?*anyopaque;
extern var lbl32Fa: ?*anyopaque;
extern var lbl32G: ?*anyopaque;
extern var lbl32Gr: ?*anyopaque;
extern var lbl32L: ?*anyopaque;
extern var lbl33F: ?*anyopaque;
extern var lbl33Fa: ?*anyopaque;
extern var lbl33G: ?*anyopaque;
extern var lbl33Gr: ?*anyopaque;
extern var lbl33L: ?*anyopaque;
extern var lbl34F: ?*anyopaque;
extern var lbl34Fa: ?*anyopaque;
extern var lbl34G: ?*anyopaque;
extern var lbl34Gr: ?*anyopaque;
extern var lbl34L: ?*anyopaque;
extern var lbl35F: ?*anyopaque;
extern var lbl35Fa: ?*anyopaque;
extern var lbl35G: ?*anyopaque;
extern var lbl35Gr: ?*anyopaque;
extern var lbl35L: ?*anyopaque;
extern var lbl36F: ?*anyopaque;
extern var lbl36Fa: ?*anyopaque;
extern var lbl36G: ?*anyopaque;
extern var lbl36Gr: ?*anyopaque;
extern var lbl36L: ?*anyopaque;
extern var lbl41F: ?*anyopaque;
extern var lbl41Fa: ?*anyopaque;
extern var lbl41G: ?*anyopaque;
extern var lbl41Gr: ?*anyopaque;
extern var lbl41L: ?*anyopaque;
extern var lbl42F: ?*anyopaque;
extern var lbl42Fa: ?*anyopaque;
extern var lbl42G: ?*anyopaque;
extern var lbl42Gr: ?*anyopaque;
extern var lbl42L: ?*anyopaque;
extern var lbl43F: ?*anyopaque;
extern var lbl43Fa: ?*anyopaque;
extern var lbl43G: ?*anyopaque;
extern var lbl43Gr: ?*anyopaque;
extern var lbl43L: ?*anyopaque;
extern var lbl44F: ?*anyopaque;
extern var lbl44Fa: ?*anyopaque;
extern var lbl44G: ?*anyopaque;
extern var lbl44Gr: ?*anyopaque;
extern var lbl44L: ?*anyopaque;
extern var lbl45F: ?*anyopaque;
extern var lbl45Fa: ?*anyopaque;
extern var lbl45G: ?*anyopaque;
extern var lbl45Gr: ?*anyopaque;
extern var lbl45L: ?*anyopaque;
extern var lbl51F: ?*anyopaque;
extern var lbl51Fa: ?*anyopaque;
extern var lbl51G: ?*anyopaque;
extern var lbl51Gr: ?*anyopaque;
extern var lbl51L: ?*anyopaque;
extern var lbl52F: ?*anyopaque;
extern var lbl52Fa: ?*anyopaque;
extern var lbl52G: ?*anyopaque;
extern var lbl52Gr: ?*anyopaque;
extern var lbl52L: ?*anyopaque;
extern var lbl53F: ?*anyopaque;
extern var lbl53Fa: ?*anyopaque;
extern var lbl53G: ?*anyopaque;
extern var lbl53Gr: ?*anyopaque;
extern var lbl53L: ?*anyopaque;
extern var lbl54F: ?*anyopaque;
extern var lbl54Fa: ?*anyopaque;
extern var lbl54G: ?*anyopaque;
extern var lbl54Gr: ?*anyopaque;
extern var lbl54L: ?*anyopaque;
extern var lbl55F: ?*anyopaque;
extern var lbl55Fa: ?*anyopaque;
extern var lbl55G: ?*anyopaque;
extern var lbl55Gr: ?*anyopaque;
extern var lbl55L: ?*anyopaque;
extern var lbl61F: ?*anyopaque;
extern var lbl61Fa: ?*anyopaque;
extern var lbl61G: ?*anyopaque;
extern var lbl61Gr: ?*anyopaque;
extern var lbl61L: ?*anyopaque;
extern var lbl62F: ?*anyopaque;
extern var lbl62Fa: ?*anyopaque;
extern var lbl62G: ?*anyopaque;
extern var lbl62Gr: ?*anyopaque;
extern var lbl62L: ?*anyopaque;
extern var lbl63F: ?*anyopaque;
extern var lbl63Fa: ?*anyopaque;
extern var lbl63G: ?*anyopaque;
extern var lbl63Gr: ?*anyopaque;
extern var lbl63L: ?*anyopaque;
extern var lbl64F: ?*anyopaque;
extern var lbl64Fa: ?*anyopaque;
extern var lbl64G: ?*anyopaque;
extern var lbl64Gr: ?*anyopaque;
extern var lbl64L: ?*anyopaque;
extern var lbl65F: ?*anyopaque;
extern var lbl65Fa: ?*anyopaque;
extern var lbl65G: ?*anyopaque;
extern var lbl65Gr: ?*anyopaque;
extern var lbl65L: ?*anyopaque;
extern var lbl71F: ?*anyopaque;
extern var lbl71Fa: ?*anyopaque;
extern var lbl71G: ?*anyopaque;
extern var lbl71Gr: ?*anyopaque;
extern var lbl71L: ?*anyopaque;
extern var lbl72F: ?*anyopaque;
extern var lbl72Fa: ?*anyopaque;
extern var lbl72G: ?*anyopaque;
extern var lbl72Gr: ?*anyopaque;
extern var lbl72L: ?*anyopaque;
extern var lbl73F: ?*anyopaque;
extern var lbl73Fa: ?*anyopaque;
extern var lbl73G: ?*anyopaque;
extern var lbl73Gr: ?*anyopaque;
extern var lbl73L: ?*anyopaque;
extern var lbl74F: ?*anyopaque;
extern var lbl74Fa: ?*anyopaque;
extern var lbl74G: ?*anyopaque;
extern var lbl74Gr: ?*anyopaque;
extern var lbl74L: ?*anyopaque;
extern var lbl75F: ?*anyopaque;
extern var lbl75Fa: ?*anyopaque;
extern var lbl75G: ?*anyopaque;
extern var lbl75Gr: ?*anyopaque;
extern var lbl75L: ?*anyopaque;
extern var lbl81F: ?*anyopaque;
extern var lbl81G: ?*anyopaque;
extern var lbl81Gr: ?*anyopaque;
extern var lbl81L: ?*anyopaque;
extern var lbl82F: ?*anyopaque;
extern var lbl82Fa: ?*anyopaque;
extern var lbl82G: ?*anyopaque;
extern var lbl82Gr: ?*anyopaque;
extern var lbl82L: ?*anyopaque;
extern var lbl83F: ?*anyopaque;
extern var lbl83Fa: ?*anyopaque;
extern var lbl83G: ?*anyopaque;
extern var lbl83Gr: ?*anyopaque;
extern var lbl83L: ?*anyopaque;
extern var lbl84F: ?*anyopaque;
extern var lbl84Fa: ?*anyopaque;
extern var lbl84G: ?*anyopaque;
extern var lbl84Gr: ?*anyopaque;
extern var lbl84L: ?*anyopaque;
extern var lbl85F: ?*anyopaque;
extern var lbl85Fa: ?*anyopaque;
extern var lbl85G: ?*anyopaque;
extern var lbl85Gr: ?*anyopaque;
extern var lbl85L: ?*anyopaque;

extern fn gtk_button_new() ?*anyopaque;
extern fn gtk_button_new_with_label(label: [*:0]const u8) ?*anyopaque;
extern fn gtk_label_new(str: [*:0]const u8) ?*anyopaque;
extern fn gtk_widget_set_tooltip_text(widget: ?*anyopaque, text: [*:0]const u8) void;
extern fn gtk_widget_set_size_request(widget: ?*anyopaque, width: c_int, height: c_int) void;
extern fn gtk_widget_set_name(widget: ?*anyopaque, name: [*:0]const u8) void;
extern fn gtk_widget_set_focus_on_click(widget: ?*anyopaque, focus_on_click: c_int) void;
extern fn gtk_fixed_put(fixed: ?*anyopaque, widget: ?*anyopaque, x: c_int, y: c_int) void;
extern fn gtk_fixed_move(fixed: ?*anyopaque, widget: ?*anyopaque, x: c_int, y: c_int) void;
extern fn gtk_widget_show_all(widget: ?*anyopaque) void;
extern fn g_signal_connect_data(instance: ?*anyopaque, detailed_signal: [*:0]const u8, c_handler: ?*const anyopaque, data: ?*anyopaque, destroy_data: ?*const anyopaque, connect_flags: c_int) c_ulong;
extern fn gtk_css_provider_new() ?*anyopaque;
extern fn gdk_display_get_default() ?*anyopaque;
extern fn gdk_display_get_default_screen(display: ?*anyopaque) ?*anyopaque;
extern fn gtk_style_context_add_provider_for_screen(screen: ?*anyopaque, provider: ?*anyopaque, priority: c_uint) void;
extern fn gtk_css_provider_load_from_data(provider: ?*anyopaque, data: [*c]const u8, length: c_long, err: *?*anyopaque) c_int;
extern fn g_object_unref(object: ?*anyopaque) void;
extern fn free(ptr: ?*anyopaque) void;
extern fn malloc(size: usize) ?*anyopaque;
extern fn exit(code: c_int) noreturn;
extern fn moreInfoOnError(m1: [*:0]const u8, m2: [*:0]const u8, m3: ?[*:0]const u8, m4: ?[*:0]const u8) void;
extern fn lcd_clear_buf() void;
extern fn check_all_btn_widgets_for_consistency() void;
extern fn z47_prepareCssData() void;
extern fn z47_setupUI_preamble() void;
extern fn z47_btnFnPressed_wrapper(a: ?*anyopaque, b: ?*anyopaque, c: ?*anyopaque) c_int;
extern fn z47_btnFnReleased_wrapper(a: ?*anyopaque, b: ?*anyopaque, c: ?*anyopaque) c_int;
extern fn z47_btnPressed_signal(a: ?*anyopaque, b: ?*anyopaque, c: ?*anyopaque) c_int;
extern fn z47_btnReleased_signal(a: ?*anyopaque, b: ?*anyopaque, c: ?*anyopaque) c_int;

fn isR47FAM() bool {
    return calcModel == USER_R47f_g or calcModel == USER_R47bk_fg or
        calcModel == USER_R47fg_bk or calcModel == USER_R47fg_g;
}

fn sig(w: ?*anyopaque, ev: [*:0]const u8, cb: ?*const anyopaque, data: [*:0]const u8) void {
    _ = g_signal_connect_data(w, ev, cb, @ptrCast(@constCast(data)), null, 0);
}

pub fn setupUI() void {
    var keyCnt: usize = 0;
    var keyCntA: usize = 0;
    var xPos: c_int = undefined;
    var yPos: c_int = undefined;

    z47_prepareCssData();

    const cssProvider = gtk_css_provider_new();
    const cssDisplay = gdk_display_get_default();
    const cssScreen = gdk_display_get_default_screen(cssDisplay);
    gtk_style_context_add_provider_for_screen(cssScreen, cssProvider, GTK_STYLE_PROVIDER_PRIORITY_USER);

    var err: ?*anyopaque = null;
    _ = gtk_css_provider_load_from_data(cssProvider, cssData, -1, &err);
    if (err != null) {
        moreInfoOnError("In function setupUI:", "error while loading CSS style sheet " ++ CSSFILE, null, null);
        exit(1);
    }
    g_object_unref(cssProvider);
    free(@ptrCast(cssData));

    z47_setupUI_preamble();

    if (enableFunctionKeysDisplay) {
        btn11 = gtk_button_new_with_label("F1");
        btn12 = gtk_button_new_with_label("F2");
        btn13 = gtk_button_new_with_label("F3");
        btn14 = gtk_button_new_with_label("F4");
        btn15 = gtk_button_new_with_label("F5");
        btn16 = gtk_button_new_with_label("F6");
    } else {
        btn11 = gtk_button_new_with_label("");
        btn12 = gtk_button_new_with_label("");
        btn13 = gtk_button_new_with_label("");
        btn14 = gtk_button_new_with_label("");
        btn15 = gtk_button_new_with_label("");
        btn16 = gtk_button_new_with_label("");
    }
    gtk_widget_set_tooltip_text(btn11, "F1");
    gtk_widget_set_tooltip_text(btn12, "F2");
    gtk_widget_set_tooltip_text(btn13, "F3");
    gtk_widget_set_tooltip_text(btn14, "F4");
    gtk_widget_set_tooltip_text(btn15, "F5");
    gtk_widget_set_tooltip_text(btn16, "F6");
    gtk_widget_set_size_request(btn11, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn12, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn13, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn14, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn15, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn16, KEY_WIDTH_1, 0);
    gtk_widget_set_name(btn11, "calcKey");
    gtk_widget_set_name(btn12, "calcKey");
    gtk_widget_set_name(btn13, "calcKey");
    gtk_widget_set_name(btn14, "calcKey");
    gtk_widget_set_name(btn15, "calcKey");
    gtk_widget_set_name(btn16, "calcKey");
    sig(btn11, "button-press-event", @ptrCast(&z47_btnFnPressed_wrapper), "1");
    sig(btn12, "button-press-event", @ptrCast(&z47_btnFnPressed_wrapper), "2");
    sig(btn13, "button-press-event", @ptrCast(&z47_btnFnPressed_wrapper), "3");
    sig(btn14, "button-press-event", @ptrCast(&z47_btnFnPressed_wrapper), "4");
    sig(btn15, "button-press-event", @ptrCast(&z47_btnFnPressed_wrapper), "5");
    sig(btn16, "button-press-event", @ptrCast(&z47_btnFnPressed_wrapper), "6");
    sig(btn11, "button-release-event", @ptrCast(&z47_btnFnReleased_wrapper), "1");
    sig(btn12, "button-release-event", @ptrCast(&z47_btnFnReleased_wrapper), "2");
    sig(btn13, "button-release-event", @ptrCast(&z47_btnFnReleased_wrapper), "3");
    sig(btn14, "button-release-event", @ptrCast(&z47_btnFnReleased_wrapper), "4");
    sig(btn15, "button-release-event", @ptrCast(&z47_btnFnReleased_wrapper), "5");
    sig(btn16, "button-release-event", @ptrCast(&z47_btnFnReleased_wrapper), "6");
    gtk_widget_set_focus_on_click(btn11, 0);
    gtk_widget_set_focus_on_click(btn12, 0);
    gtk_widget_set_focus_on_click(btn13, 0);
    gtk_widget_set_focus_on_click(btn14, 0);
    gtk_widget_set_focus_on_click(btn15, 0);
    gtk_widget_set_focus_on_click(btn16, 0);
    xPos = X_LEFT_PORTRAIT;
    yPos = Y_TOP_PORTRAIT;
    gtk_fixed_put(grid, btn11, xPos, yPos);
    xPos += DELTA_KEYS_X;
    gtk_fixed_put(grid, btn12, xPos, yPos);
    xPos += DELTA_KEYS_X;
    gtk_fixed_put(grid, btn13, xPos, yPos);
    xPos += DELTA_KEYS_X;
    gtk_fixed_put(grid, btn14, xPos, yPos);
    xPos += DELTA_KEYS_X;
    gtk_fixed_put(grid, btn15, xPos, yPos);
    xPos += DELTA_KEYS_X;
    gtk_fixed_put(grid, btn16, xPos, yPos);
    btn21 = gtk_button_new();
    btn22 = gtk_button_new();
    btn23 = gtk_button_new();
    btn24 = gtk_button_new();
    btn25 = gtk_button_new();
    btn26 = gtk_button_new();
    gtk_widget_set_tooltip_text(btn21, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn22, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn23, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn24, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn25, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn26, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    btn21A = gtk_button_new();
    btn22A = gtk_button_new();
    btn23A = gtk_button_new();
    btn24A = gtk_button_new();
    btn25A = gtk_button_new();
    btn26A = gtk_button_new();
    gtk_widget_set_tooltip_text(btn21A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn22A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn23A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn24A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn25A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn26A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    lbl21F = gtk_label_new("");
    lbl22F = gtk_label_new("");
    lbl23F = gtk_label_new("");
    lbl24F = gtk_label_new("");
    lbl25F = gtk_label_new("");
    lbl26F = gtk_label_new("");
    lbl21Fa = gtk_label_new("");
    lbl22Fa = gtk_label_new("");
    lbl23Fa = gtk_label_new("");
    lbl24Fa = gtk_label_new("");
    lbl25Fa = gtk_label_new("");
    lbl26Fa = gtk_label_new("");
    lbl21G = gtk_label_new("");
    lbl22G = gtk_label_new("");
    lbl23G = gtk_label_new("");
    lbl24G = gtk_label_new("");
    lbl25G = gtk_label_new("");
    lbl26G = gtk_label_new("");
    lbl21L = gtk_label_new("");
    lbl22L = gtk_label_new("");
    lbl23L = gtk_label_new("");
    lbl24L = gtk_label_new("");
    lbl25L = gtk_label_new("");
    lbl26L = gtk_label_new("");
    lbl21Gr = gtk_label_new("");
    lbl22Gr = gtk_label_new("");
    lbl23Gr = gtk_label_new("");
    lbl24Gr = gtk_label_new("");
    lbl25Gr = gtk_label_new("");
    lbl26Gr = gtk_label_new("");
    gtk_widget_set_size_request(btn21, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn22, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn23, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn24, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn25, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn26, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn21A, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn22A, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn23A, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn24A, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn25A, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn26A, KEY_WIDTH_1, 0);
    sig(btn21, "button-press-event", @ptrCast(&z47_btnPressed_signal), "00");
    sig(btn22, "button-press-event", @ptrCast(&z47_btnPressed_signal), "01");
    sig(btn23, "button-press-event", @ptrCast(&z47_btnPressed_signal), "02");
    sig(btn24, "button-press-event", @ptrCast(&z47_btnPressed_signal), "03");
    sig(btn25, "button-press-event", @ptrCast(&z47_btnPressed_signal), "04");
    sig(btn26, "button-press-event", @ptrCast(&z47_btnPressed_signal), "05");
    sig(btn21, "button-release-event", @ptrCast(&z47_btnReleased_signal), "00");
    sig(btn22, "button-release-event", @ptrCast(&z47_btnReleased_signal), "01");
    sig(btn23, "button-release-event", @ptrCast(&z47_btnReleased_signal), "02");
    sig(btn24, "button-release-event", @ptrCast(&z47_btnReleased_signal), "03");
    sig(btn25, "button-release-event", @ptrCast(&z47_btnReleased_signal), "04");
    sig(btn26, "button-release-event", @ptrCast(&z47_btnReleased_signal), "05");
    sig(btn21A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "00");
    sig(btn22A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "01");
    sig(btn23A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "02");
    sig(btn24A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "03");
    sig(btn25A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "04");
    sig(btn26A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "05");
    sig(btn21A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "00");
    sig(btn22A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "01");
    sig(btn23A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "02");
    sig(btn24A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "03");
    sig(btn25A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "04");
    sig(btn26A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "05");
    gtk_fixed_put(grid, lbl21F, 0, 0);
    gtk_fixed_put(grid, lbl22F, 0, 0);
    gtk_fixed_put(grid, lbl23F, 0, 0);
    gtk_fixed_put(grid, lbl24F, 0, 0);
    gtk_fixed_put(grid, lbl25F, 0, 0);
    gtk_fixed_put(grid, lbl26F, 0, 0);
    gtk_fixed_put(grid, lbl21G, 0, 0);
    gtk_fixed_put(grid, lbl22G, 0, 0);
    gtk_fixed_put(grid, lbl23G, 0, 0);
    gtk_fixed_put(grid, lbl24G, 0, 0);
    gtk_fixed_put(grid, lbl25G, 0, 0);
    gtk_fixed_put(grid, lbl26G, 0, 0);
    gtk_fixed_put(grid, lbl21Fa, 0, 0);
    gtk_fixed_put(grid, lbl22Fa, 0, 0);
    gtk_fixed_put(grid, lbl23Fa, 0, 0);
    gtk_fixed_put(grid, lbl24Fa, 0, 0);
    gtk_fixed_put(grid, lbl25Fa, 0, 0);
    gtk_fixed_put(grid, lbl26Fa, 0, 0);
    gtk_fixed_put(grid, lbl21Gr, 0, 0);
    gtk_fixed_put(grid, lbl22Gr, 0, 0);
    gtk_fixed_put(grid, lbl23Gr, 0, 0);
    gtk_fixed_put(grid, lbl24Gr, 0, 0);
    gtk_fixed_put(grid, lbl25Gr, 0, 0);
    gtk_fixed_put(grid, lbl26Gr, 0, 0);
    if (calcLandscape) {
        xPos = X_LEFT_LANDSCAPE;
        yPos = Y_TOP_LANDSCAPE;
    } else {
        xPos = X_LEFT_PORTRAIT;
        yPos += DELTA_KEYS_Y;
    }
    gtk_fixed_put(grid, btn21, xPos, yPos);
    gtk_fixed_put(grid, lbl21L, xPos + KEY_WIDTH_1 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn21A, xPos, yPos);
    xPos += DELTA_KEYS_X;
    gtk_fixed_put(grid, btn22, xPos, yPos);
    gtk_fixed_put(grid, lbl22L, xPos + KEY_WIDTH_1 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn22A, xPos, yPos);
    xPos += DELTA_KEYS_X;
    gtk_fixed_put(grid, btn23, xPos, yPos);
    gtk_fixed_put(grid, lbl23L, xPos + KEY_WIDTH_1 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn23A, xPos, yPos);
    xPos += DELTA_KEYS_X;
    gtk_fixed_put(grid, btn24, xPos, yPos);
    gtk_fixed_put(grid, lbl24L, xPos + KEY_WIDTH_1 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn24A, xPos, yPos);
    xPos += DELTA_KEYS_X;
    gtk_fixed_put(grid, btn25, xPos, yPos);
    gtk_fixed_put(grid, lbl25L, xPos + KEY_WIDTH_1 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn25A, xPos, yPos);
    xPos += DELTA_KEYS_X;
    gtk_fixed_put(grid, btn26, xPos, yPos);
    gtk_fixed_put(grid, lbl26L, xPos + KEY_WIDTH_1 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn26A, xPos, yPos);
    btn31 = gtk_button_new();
    btn32 = gtk_button_new();
    btn33 = gtk_button_new();
    btn34 = gtk_button_new();
    btn35 = gtk_button_new();
    btn36 = gtk_button_new();
    gtk_widget_set_tooltip_text(btn31, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn32, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn33, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn34, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn35, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn36, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    btn31A = gtk_button_new();
    btn32A = gtk_button_new();
    btn33A = gtk_button_new();
    btn34A = gtk_button_new();
    btn35A = gtk_button_new();
    btn36A = gtk_button_new();
    gtk_widget_set_tooltip_text(btn31A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn32A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn33A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn34A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn35A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn36A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    lbl31F = gtk_label_new("");
    lbl32F = gtk_label_new("");
    lbl33F = gtk_label_new("");
    lbl34F = gtk_label_new("");
    lbl35F = gtk_label_new("");
    lbl36F = gtk_label_new("");
    lbl31Fa = gtk_label_new("");
    lbl32Fa = gtk_label_new("");
    lbl33Fa = gtk_label_new("");
    lbl34Fa = gtk_label_new("");
    lbl35Fa = gtk_label_new("");
    lbl36Fa = gtk_label_new("");
    lbl31G = gtk_label_new("");
    lbl32G = gtk_label_new("");
    lbl33G = gtk_label_new("");
    lbl34G = gtk_label_new("");
    lbl35G = gtk_label_new("");
    lbl36G = gtk_label_new("");
    lbl31L = gtk_label_new("");
    lbl32L = gtk_label_new("");
    lbl33L = gtk_label_new("");
    lbl34L = gtk_label_new("");
    lbl35L = gtk_label_new("");
    lbl36L = gtk_label_new("");
    lbl31Gr = gtk_label_new("");
    lbl32Gr = gtk_label_new("");
    lbl33Gr = gtk_label_new("");
    lbl34Gr = gtk_label_new("");
    lbl35Gr = gtk_label_new("");
    lbl36Gr = gtk_label_new("");
    gtk_widget_set_size_request(btn31, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn32, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn33, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn34, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn35, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn36, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn31A, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn32A, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn33A, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn34A, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn35A, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn36A, KEY_WIDTH_1, 0);
    sig(btn31, "button-press-event", @ptrCast(&z47_btnPressed_signal), "06");
    sig(btn32, "button-press-event", @ptrCast(&z47_btnPressed_signal), "07");
    sig(btn33, "button-press-event", @ptrCast(&z47_btnPressed_signal), "08");
    sig(btn34, "button-press-event", @ptrCast(&z47_btnPressed_signal), "09");
    sig(btn35, "button-press-event", @ptrCast(&z47_btnPressed_signal), "10");
    sig(btn36, "button-press-event", @ptrCast(&z47_btnPressed_signal), "11");
    sig(btn31, "button-release-event", @ptrCast(&z47_btnReleased_signal), "06");
    sig(btn32, "button-release-event", @ptrCast(&z47_btnReleased_signal), "07");
    sig(btn33, "button-release-event", @ptrCast(&z47_btnReleased_signal), "08");
    sig(btn34, "button-release-event", @ptrCast(&z47_btnReleased_signal), "09");
    sig(btn35, "button-release-event", @ptrCast(&z47_btnReleased_signal), "10");
    sig(btn36, "button-release-event", @ptrCast(&z47_btnReleased_signal), "11");
    sig(btn31A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "06");
    sig(btn32A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "07");
    sig(btn33A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "08");
    sig(btn34A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "09");
    sig(btn35A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "10");
    sig(btn36A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "11");
    sig(btn31A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "06");
    sig(btn32A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "07");
    sig(btn33A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "08");
    sig(btn34A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "09");
    sig(btn35A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "10");
    sig(btn36A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "11");
    gtk_fixed_put(grid, lbl31F, 0, 0);
    gtk_fixed_put(grid, lbl32F, 0, 0);
    gtk_fixed_put(grid, lbl33F, 0, 0);
    gtk_fixed_put(grid, lbl34F, 0, 0);
    gtk_fixed_put(grid, lbl35F, 0, 0);
    gtk_fixed_put(grid, lbl36F, 0, 0);
    gtk_fixed_put(grid, lbl31Fa, 0, 0);
    gtk_fixed_put(grid, lbl32Fa, 0, 0);
    gtk_fixed_put(grid, lbl33Fa, 0, 0);
    gtk_fixed_put(grid, lbl34Fa, 0, 0);
    gtk_fixed_put(grid, lbl35Fa, 0, 0);
    gtk_fixed_put(grid, lbl36Fa, 0, 0);
    gtk_fixed_put(grid, lbl31G, 0, 0);
    gtk_fixed_put(grid, lbl32G, 0, 0);
    gtk_fixed_put(grid, lbl33G, 0, 0);
    gtk_fixed_put(grid, lbl34G, 0, 0);
    gtk_fixed_put(grid, lbl35G, 0, 0);
    gtk_fixed_put(grid, lbl36G, 0, 0);
    gtk_fixed_put(grid, lbl31Gr, 0, 0);
    gtk_fixed_put(grid, lbl32Gr, 0, 0);
    gtk_fixed_put(grid, lbl33Gr, 0, 0);
    gtk_fixed_put(grid, lbl34Gr, 0, 0);
    gtk_fixed_put(grid, lbl35Gr, 0, 0);
    gtk_fixed_put(grid, lbl36Gr, 0, 0);
    xPos = if (calcLandscape) X_LEFT_LANDSCAPE else X_LEFT_PORTRAIT;
    yPos += DELTA_KEYS_Y;
    gtk_fixed_put(grid, btn31, xPos, yPos);
    gtk_fixed_put(grid, lbl31L, xPos + KEY_WIDTH_1 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn31A, xPos, yPos);
    xPos += DELTA_KEYS_X;
    gtk_fixed_put(grid, btn32, xPos, yPos);
    gtk_fixed_put(grid, lbl32L, xPos + KEY_WIDTH_1 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn32A, xPos, yPos);
    xPos += DELTA_KEYS_X;
    gtk_fixed_put(grid, btn33, xPos, yPos);
    gtk_fixed_put(grid, lbl33L, xPos + KEY_WIDTH_1 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn33A, xPos, yPos);
    xPos += DELTA_KEYS_X;
    gtk_fixed_put(grid, btn34, xPos, yPos);
    gtk_fixed_put(grid, lbl34L, xPos + KEY_WIDTH_1 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn34A, xPos, yPos);
    xPos += DELTA_KEYS_X;
    gtk_fixed_put(grid, btn35, xPos, yPos);
    gtk_fixed_put(grid, lbl35L, xPos + KEY_WIDTH_1 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn35A, xPos, yPos);
    xPos += DELTA_KEYS_X;
    gtk_fixed_put(grid, btn36, xPos, yPos);
    gtk_fixed_put(grid, lbl36L, xPos + KEY_WIDTH_1 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn36A, xPos, yPos);
    btn41 = gtk_button_new();
    btn42 = gtk_button_new();
    btn43 = gtk_button_new();
    btn44 = gtk_button_new();
    btn45 = gtk_button_new();
    gtk_widget_set_tooltip_text(btn41, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn42, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn43, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn44, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn45, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    btn42A = gtk_button_new();
    btn43A = gtk_button_new();
    btn44A = gtk_button_new();
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn42A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn43A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn44A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    keyCntA += 1;
    lbl41F = gtk_label_new("");
    lbl42F = gtk_label_new("");
    lbl43F = gtk_label_new("");
    lbl44F = gtk_label_new("");
    lbl45F = gtk_label_new("");
    lbl41Fa = gtk_label_new("");
    lbl42Fa = gtk_label_new("");
    lbl43Fa = gtk_label_new("");
    lbl44Fa = gtk_label_new("");
    lbl45Fa = gtk_label_new("");
    lbl41G = gtk_label_new("");
    lbl42G = gtk_label_new("");
    lbl43G = gtk_label_new("");
    lbl44G = gtk_label_new("");
    lbl45G = gtk_label_new("");
    lbl41L = gtk_label_new("");
    lbl42L = gtk_label_new("");
    lbl43L = gtk_label_new("");
    lbl44L = gtk_label_new("");
    lbl45L = gtk_label_new("");
    lbl41Gr = gtk_label_new("");
    lbl42Gr = gtk_label_new("");
    lbl43Gr = gtk_label_new("");
    lbl44Gr = gtk_label_new("");
    lbl45Gr = gtk_label_new("");
    gtk_widget_set_size_request(btn41, KEY_WIDTH_1 + DELTA_KEYS_X, 0);
    gtk_widget_set_size_request(btn42, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn43, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn44, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn45, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn42A, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn43A, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn44A, KEY_WIDTH_1, 0);
    sig(btn41, "button-press-event", @ptrCast(&z47_btnPressed_signal), "12");
    sig(btn42, "button-press-event", @ptrCast(&z47_btnPressed_signal), "13");
    sig(btn43, "button-press-event", @ptrCast(&z47_btnPressed_signal), "14");
    sig(btn44, "button-press-event", @ptrCast(&z47_btnPressed_signal), "15");
    sig(btn45, "button-press-event", @ptrCast(&z47_btnPressed_signal), "16");
    sig(btn41, "button-release-event", @ptrCast(&z47_btnReleased_signal), "12");
    sig(btn42, "button-release-event", @ptrCast(&z47_btnReleased_signal), "13");
    sig(btn43, "button-release-event", @ptrCast(&z47_btnReleased_signal), "14");
    sig(btn44, "button-release-event", @ptrCast(&z47_btnReleased_signal), "15");
    sig(btn45, "button-release-event", @ptrCast(&z47_btnReleased_signal), "16");
    sig(btn42A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "13");
    sig(btn43A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "14");
    sig(btn44A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "15");
    sig(btn42A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "13");
    sig(btn43A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "14");
    sig(btn44A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "15");
    gtk_fixed_put(grid, lbl41F, 0, 0);
    gtk_fixed_put(grid, lbl42F, 0, 0);
    gtk_fixed_put(grid, lbl43F, 0, 0);
    gtk_fixed_put(grid, lbl44F, 0, 0);
    gtk_fixed_put(grid, lbl45F, 0, 0);
    gtk_fixed_put(grid, lbl41Fa, 0, 0);
    gtk_fixed_put(grid, lbl42Fa, 0, 0);
    gtk_fixed_put(grid, lbl43Fa, 0, 0);
    gtk_fixed_put(grid, lbl44Fa, 0, 0);
    gtk_fixed_put(grid, lbl45Fa, 0, 0);
    gtk_fixed_put(grid, lbl41G, 0, 0);
    gtk_fixed_put(grid, lbl42G, 0, 0);
    gtk_fixed_put(grid, lbl43G, 0, 0);
    gtk_fixed_put(grid, lbl44G, 0, 0);
    gtk_fixed_put(grid, lbl45G, 0, 0);
    gtk_fixed_put(grid, lbl41Gr, 0, 0);
    gtk_fixed_put(grid, lbl42Gr, 0, 0);
    gtk_fixed_put(grid, lbl43Gr, 0, 0);
    gtk_fixed_put(grid, lbl44Gr, 0, 0);
    gtk_fixed_put(grid, lbl45Gr, 0, 0);
    xPos = if (calcLandscape) X_LEFT_LANDSCAPE else X_LEFT_PORTRAIT;
    yPos += DELTA_KEYS_Y;
    gtk_fixed_put(grid, btn41, xPos, yPos);
    gtk_fixed_put(grid, lbl41L, xPos + KEY_WIDTH_1 + DELTA_KEYS_X + 4, yPos + Y_OFFSET_LETTER);
    xPos += DELTA_KEYS_X * 2;
    gtk_fixed_put(grid, btn42, xPos, yPos);
    gtk_fixed_put(grid, lbl42L, xPos + KEY_WIDTH_1 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn42A, xPos, yPos);
    xPos += DELTA_KEYS_X;
    gtk_fixed_put(grid, btn43, xPos, yPos);
    gtk_fixed_put(grid, lbl43L, xPos + KEY_WIDTH_1 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn43A, xPos, yPos);
    xPos += DELTA_KEYS_X;
    gtk_fixed_put(grid, btn44, xPos, yPos);
    gtk_fixed_put(grid, lbl44L, xPos + KEY_WIDTH_1 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn44A, xPos, yPos);
    xPos += DELTA_KEYS_X;
    gtk_fixed_put(grid, btn45, xPos, yPos);
    gtk_fixed_put(grid, lbl45L, xPos + KEY_WIDTH_1 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    btn51 = gtk_button_new();
    btn52 = gtk_button_new();
    btn53 = gtk_button_new();
    btn54 = gtk_button_new();
    btn55 = gtk_button_new();
    gtk_widget_set_tooltip_text(btn51, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn52, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn53, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn54, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn55, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    btn52A = gtk_button_new();
    btn53A = gtk_button_new();
    btn54A = gtk_button_new();
    btn55A = gtk_button_new();
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn52A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn53A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn54A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn55A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    lbl51F = gtk_label_new("");
    lbl52F = gtk_label_new("");
    lbl53F = gtk_label_new("");
    lbl54F = gtk_label_new("");
    lbl55F = gtk_label_new("");
    lbl51Fa = gtk_label_new("");
    lbl52Fa = gtk_label_new("");
    lbl53Fa = gtk_label_new("");
    lbl54Fa = gtk_label_new("");
    lbl55Fa = gtk_label_new("");
    lbl51G = gtk_label_new("");
    lbl52G = gtk_label_new("");
    lbl53G = gtk_label_new("");
    lbl54G = gtk_label_new("");
    lbl55G = gtk_label_new("");
    lbl51L = gtk_label_new("");
    lbl52L = gtk_label_new("");
    lbl53L = gtk_label_new("");
    lbl54L = gtk_label_new("");
    lbl55L = gtk_label_new("");
    lbl51Gr = gtk_label_new("");
    lbl52Gr = gtk_label_new("");
    lbl53Gr = gtk_label_new("");
    lbl54Gr = gtk_label_new("");
    lbl55Gr = gtk_label_new("");
    gtk_widget_set_size_request(btn51, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn52, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn53, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn54, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn55, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn52A, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn53A, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn54A, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn55A, KEY_WIDTH_2, 0);
    sig(btn51, "button-press-event", @ptrCast(&z47_btnPressed_signal), "17");
    sig(btn52, "button-press-event", @ptrCast(&z47_btnPressed_signal), "18");
    sig(btn53, "button-press-event", @ptrCast(&z47_btnPressed_signal), "19");
    sig(btn54, "button-press-event", @ptrCast(&z47_btnPressed_signal), "20");
    sig(btn55, "button-press-event", @ptrCast(&z47_btnPressed_signal), "21");
    sig(btn51, "button-release-event", @ptrCast(&z47_btnReleased_signal), "17");
    sig(btn52, "button-release-event", @ptrCast(&z47_btnReleased_signal), "18");
    sig(btn53, "button-release-event", @ptrCast(&z47_btnReleased_signal), "19");
    sig(btn54, "button-release-event", @ptrCast(&z47_btnReleased_signal), "20");
    sig(btn55, "button-release-event", @ptrCast(&z47_btnReleased_signal), "21");
    sig(btn52A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "18");
    sig(btn53A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "19");
    sig(btn54A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "20");
    sig(btn55A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "21");
    sig(btn52A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "18");
    sig(btn53A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "19");
    sig(btn54A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "20");
    sig(btn55A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "21");
    gtk_fixed_put(grid, lbl51F, 0, 0);
    gtk_fixed_put(grid, lbl52F, 0, 0);
    gtk_fixed_put(grid, lbl53F, 0, 0);
    gtk_fixed_put(grid, lbl54F, 0, 0);
    gtk_fixed_put(grid, lbl55F, 0, 0);
    gtk_fixed_put(grid, lbl51Fa, 0, 0);
    gtk_fixed_put(grid, lbl52Fa, 0, 0);
    gtk_fixed_put(grid, lbl53Fa, 0, 0);
    gtk_fixed_put(grid, lbl54Fa, 0, 0);
    gtk_fixed_put(grid, lbl55Fa, 0, 0);
    gtk_fixed_put(grid, lbl51G, 0, 0);
    gtk_fixed_put(grid, lbl52G, 0, 0);
    gtk_fixed_put(grid, lbl53G, 0, 0);
    gtk_fixed_put(grid, lbl54G, 0, 0);
    gtk_fixed_put(grid, lbl55G, 0, 0);
    gtk_fixed_put(grid, lbl51Gr, 0, 0);
    gtk_fixed_put(grid, lbl52Gr, 0, 0);
    gtk_fixed_put(grid, lbl53Gr, 0, 0);
    gtk_fixed_put(grid, lbl54Gr, 0, 0);
    gtk_fixed_put(grid, lbl55Gr, 0, 0);
    xPos = if (calcLandscape) X_LEFT_LANDSCAPE else X_LEFT_PORTRAIT;
    yPos += DELTA_KEYS_Y + 1;
    gtk_fixed_put(grid, btn51, xPos, yPos);
    xPos += DELTA_KEYS_X + LARGE_KEY_SPACING_1;
    gtk_fixed_put(grid, btn52, xPos, yPos);
    gtk_fixed_put(grid, lbl52L, xPos + KEY_WIDTH_2 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn52A, xPos, yPos);
    xPos += DELTA_KEYS_X + LARGE_KEY_SPACING_2;
    gtk_fixed_put(grid, btn53, xPos, yPos);
    gtk_fixed_put(grid, lbl53L, xPos + KEY_WIDTH_2 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn53A, xPos, yPos);
    xPos += DELTA_KEYS_X + LARGE_KEY_SPACING_2;
    gtk_fixed_put(grid, btn54, xPos, yPos);
    gtk_fixed_put(grid, lbl54L, xPos + KEY_WIDTH_2 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn54A, xPos, yPos);
    xPos += DELTA_KEYS_X + LARGE_KEY_SPACING_2;
    gtk_fixed_put(grid, btn55, xPos, yPos);
    gtk_fixed_put(grid, lbl55L, xPos + KEY_WIDTH_2 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn55A, xPos, yPos);
    btn61 = gtk_button_new();
    btn62 = gtk_button_new();
    btn63 = gtk_button_new();
    btn64 = gtk_button_new();
    btn65 = gtk_button_new();
    gtk_widget_set_tooltip_text(btn61, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn62, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn63, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn64, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn65, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    btn62A = gtk_button_new();
    btn63A = gtk_button_new();
    btn64A = gtk_button_new();
    btn65A = gtk_button_new();
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn62A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn63A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn64A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn65A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    lbl61F = gtk_label_new("");
    lbl62F = gtk_label_new("");
    lbl63F = gtk_label_new("");
    lbl64F = gtk_label_new("");
    lbl65F = gtk_label_new("");
    lbl61Fa = gtk_label_new("");
    lbl62Fa = gtk_label_new("");
    lbl63Fa = gtk_label_new("");
    lbl64Fa = gtk_label_new("");
    lbl65Fa = gtk_label_new("");
    lbl61G = gtk_label_new("");
    lbl62G = gtk_label_new("");
    lbl63G = gtk_label_new("");
    lbl64G = gtk_label_new("");
    lbl65G = gtk_label_new("");
    lbl61L = gtk_label_new("");
    lbl62L = gtk_label_new("");
    lbl63L = gtk_label_new("");
    lbl64L = gtk_label_new("");
    lbl65L = gtk_label_new("");
    lbl61Gr = gtk_label_new("");
    lbl62Gr = gtk_label_new("");
    lbl63Gr = gtk_label_new("");
    lbl64Gr = gtk_label_new("");
    lbl65Gr = gtk_label_new("");
    gtk_widget_set_size_request(btn61, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn62, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn63, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn64, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn65, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn62A, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn63A, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn64A, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn65A, KEY_WIDTH_2, 0);
    sig(btn61, "button-press-event", @ptrCast(&z47_btnPressed_signal), "22");
    sig(btn62, "button-press-event", @ptrCast(&z47_btnPressed_signal), "23");
    sig(btn63, "button-press-event", @ptrCast(&z47_btnPressed_signal), "24");
    sig(btn64, "button-press-event", @ptrCast(&z47_btnPressed_signal), "25");
    sig(btn65, "button-press-event", @ptrCast(&z47_btnPressed_signal), "26");
    sig(btn61, "button-release-event", @ptrCast(&z47_btnReleased_signal), "22");
    sig(btn62, "button-release-event", @ptrCast(&z47_btnReleased_signal), "23");
    sig(btn63, "button-release-event", @ptrCast(&z47_btnReleased_signal), "24");
    sig(btn64, "button-release-event", @ptrCast(&z47_btnReleased_signal), "25");
    sig(btn65, "button-release-event", @ptrCast(&z47_btnReleased_signal), "26");
    sig(btn62A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "23");
    sig(btn63A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "24");
    sig(btn64A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "25");
    sig(btn65A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "26");
    sig(btn62A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "23");
    sig(btn63A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "24");
    sig(btn64A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "25");
    sig(btn65A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "26");
    gtk_fixed_put(grid, lbl61F, 0, 0);
    gtk_fixed_put(grid, lbl62F, 0, 0);
    gtk_fixed_put(grid, lbl63F, 0, 0);
    gtk_fixed_put(grid, lbl64F, 0, 0);
    gtk_fixed_put(grid, lbl61Fa, 0, 0);
    gtk_fixed_put(grid, lbl62Fa, 0, 0);
    gtk_fixed_put(grid, lbl63Fa, 0, 0);
    gtk_fixed_put(grid, lbl64Fa, 0, 0);
    gtk_fixed_put(grid, lbl65Fa, 0, 0);
    gtk_fixed_put(grid, lbl65F, 0, 0);
    gtk_fixed_put(grid, lbl61G, 0, 0);
    gtk_fixed_put(grid, lbl62G, 0, 0);
    gtk_fixed_put(grid, lbl63G, 0, 0);
    gtk_fixed_put(grid, lbl64G, 0, 0);
    gtk_fixed_put(grid, lbl65G, 0, 0);
    gtk_fixed_put(grid, lbl61Gr, 0, 0);
    gtk_fixed_put(grid, lbl62Gr, 0, 0);
    gtk_fixed_put(grid, lbl63Gr, 0, 0);
    gtk_fixed_put(grid, lbl64Gr, 0, 0);
    gtk_fixed_put(grid, lbl65Gr, 0, 0);
    xPos = if (calcLandscape) X_LEFT_LANDSCAPE else X_LEFT_PORTRAIT;
    yPos += DELTA_KEYS_Y + 1;
    gtk_fixed_put(grid, btn61, xPos, yPos);
    xPos += DELTA_KEYS_X + LARGE_KEY_SPACING_1;
    gtk_fixed_put(grid, btn62, xPos, yPos);
    gtk_fixed_put(grid, lbl62L, xPos + KEY_WIDTH_2 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn62A, xPos, yPos);
    xPos += DELTA_KEYS_X + LARGE_KEY_SPACING_2;
    gtk_fixed_put(grid, btn63, xPos, yPos);
    gtk_fixed_put(grid, lbl63L, xPos + KEY_WIDTH_2 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn63A, xPos, yPos);
    xPos += DELTA_KEYS_X + LARGE_KEY_SPACING_2;
    gtk_fixed_put(grid, btn64, xPos, yPos);
    gtk_fixed_put(grid, lbl64L, xPos + KEY_WIDTH_2 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn64A, xPos, yPos);
    xPos += DELTA_KEYS_X + LARGE_KEY_SPACING_2;
    gtk_fixed_put(grid, btn65, xPos, yPos);
    gtk_fixed_put(grid, lbl65L, xPos + KEY_WIDTH_2 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn65A, xPos, yPos);
    btn71 = gtk_button_new();
    btn72 = gtk_button_new();
    btn73 = gtk_button_new();
    btn74 = gtk_button_new();
    btn75 = gtk_button_new();
    gtk_widget_set_tooltip_text(btn71, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn72, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn73, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn74, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn75, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    btn71A = gtk_button_new();
    btn72A = gtk_button_new();
    btn73A = gtk_button_new();
    btn74A = gtk_button_new();
    btn75A = gtk_button_new();
    gtk_widget_set_tooltip_text(btn71A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn72A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn73A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn74A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn75A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    lbl71F = gtk_label_new("");
    lbl72F = gtk_label_new("");
    lbl73F = gtk_label_new("");
    lbl74F = gtk_label_new("");
    lbl75F = gtk_label_new("");
    lbl71Fa = gtk_label_new("");
    lbl72Fa = gtk_label_new("");
    lbl73Fa = gtk_label_new("");
    lbl74Fa = gtk_label_new("");
    lbl75Fa = gtk_label_new("");
    lbl71G = gtk_label_new("");
    lbl72G = gtk_label_new("");
    lbl73G = gtk_label_new("");
    lbl74G = gtk_label_new("");
    lbl75G = gtk_label_new("");
    lbl71L = gtk_label_new("");
    lbl72L = gtk_label_new("");
    lbl73L = gtk_label_new("");
    lbl74L = gtk_label_new("");
    lbl75L = gtk_label_new("");
    lbl71Gr = gtk_label_new("");
    lbl72Gr = gtk_label_new("");
    lbl73Gr = gtk_label_new("");
    lbl74Gr = gtk_label_new("");
    lbl75Gr = gtk_label_new("");
    gtk_widget_set_size_request(btn71, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn71A, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn72, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn73, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn74, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn75, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn72A, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn73A, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn74A, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn75A, KEY_WIDTH_2, 0);
    sig(btn71, "button-press-event", @ptrCast(&z47_btnPressed_signal), "27");
    sig(btn72, "button-press-event", @ptrCast(&z47_btnPressed_signal), "28");
    sig(btn73, "button-press-event", @ptrCast(&z47_btnPressed_signal), "29");
    sig(btn74, "button-press-event", @ptrCast(&z47_btnPressed_signal), "30");
    sig(btn75, "button-press-event", @ptrCast(&z47_btnPressed_signal), "31");
    sig(btn71, "button-release-event", @ptrCast(&z47_btnReleased_signal), "27");
    sig(btn72, "button-release-event", @ptrCast(&z47_btnReleased_signal), "28");
    sig(btn73, "button-release-event", @ptrCast(&z47_btnReleased_signal), "29");
    sig(btn74, "button-release-event", @ptrCast(&z47_btnReleased_signal), "30");
    sig(btn75, "button-release-event", @ptrCast(&z47_btnReleased_signal), "31");
    sig(btn71A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "27");
    sig(btn72A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "28");
    sig(btn73A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "29");
    sig(btn74A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "30");
    sig(btn75A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "31");
    sig(btn71A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "27");
    sig(btn72A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "28");
    sig(btn73A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "29");
    sig(btn74A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "30");
    sig(btn75A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "31");
    gtk_fixed_put(grid, lbl71F, 0, 0);
    gtk_fixed_put(grid, lbl72F, 0, 0);
    gtk_fixed_put(grid, lbl73F, 0, 0);
    gtk_fixed_put(grid, lbl74F, 0, 0);
    gtk_fixed_put(grid, lbl75F, 0, 0);
    gtk_fixed_put(grid, lbl71Fa, 0, 0);
    gtk_fixed_put(grid, lbl72Fa, 0, 0);
    gtk_fixed_put(grid, lbl73Fa, 0, 0);
    gtk_fixed_put(grid, lbl74Fa, 0, 0);
    gtk_fixed_put(grid, lbl75Fa, 0, 0);
    gtk_fixed_put(grid, lbl71G, 0, 0);
    gtk_fixed_put(grid, lbl72G, 0, 0);
    gtk_fixed_put(grid, lbl73G, 0, 0);
    gtk_fixed_put(grid, lbl74G, 0, 0);
    gtk_fixed_put(grid, lbl75G, 0, 0);
    gtk_fixed_put(grid, lbl71Gr, 0, 0);
    gtk_fixed_put(grid, lbl72Gr, 0, 0);
    gtk_fixed_put(grid, lbl73Gr, 0, 0);
    gtk_fixed_put(grid, lbl74Gr, 0, 0);
    gtk_fixed_put(grid, lbl75Gr, 0, 0);
    xPos = if (calcLandscape) X_LEFT_LANDSCAPE else X_LEFT_PORTRAIT;
    yPos += DELTA_KEYS_Y + 1;
    gtk_fixed_put(grid, btn71, xPos, yPos);
    gtk_fixed_put(grid, btn71A, xPos, yPos);
    xPos += DELTA_KEYS_X + LARGE_KEY_SPACING_1;
    gtk_fixed_put(grid, btn72, xPos, yPos);
    gtk_fixed_put(grid, lbl72L, xPos + KEY_WIDTH_2 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn72A, xPos, yPos);
    xPos += DELTA_KEYS_X + LARGE_KEY_SPACING_2;
    gtk_fixed_put(grid, btn73, xPos, yPos);
    gtk_fixed_put(grid, lbl73L, xPos + KEY_WIDTH_2 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn73A, xPos, yPos);
    xPos += DELTA_KEYS_X + LARGE_KEY_SPACING_2;
    gtk_fixed_put(grid, btn74, xPos, yPos);
    gtk_fixed_put(grid, lbl74L, xPos + KEY_WIDTH_2 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn74A, xPos, yPos);
    xPos += DELTA_KEYS_X + LARGE_KEY_SPACING_2;
    gtk_fixed_put(grid, btn75, xPos, yPos);
    gtk_fixed_put(grid, lbl75L, xPos + KEY_WIDTH_2 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn75A, xPos, yPos);
    btn81 = gtk_button_new();
    btn82 = gtk_button_new();
    btn83 = gtk_button_new();
    btn84 = gtk_button_new();
    btn85 = gtk_button_new();
    gtk_widget_set_tooltip_text(btn81, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn82, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn83, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn84, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    gtk_widget_set_tooltip_text(btn85, @ptrCast(if (isR47FAM()) &shortCutString[keyCnt].R47 else &shortCutString[keyCnt].C47));
    keyCnt += 1;
    btn82A = gtk_button_new();
    btn83A = gtk_button_new();
    btn84A = gtk_button_new();
    btn85A = gtk_button_new();
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn82A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn83A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn84A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    gtk_widget_set_tooltip_text(btn85A, @ptrCast(if (isR47FAM()) &shortCutString[keyCntA].R47A else &shortCutString[keyCntA].C47A));
    keyCntA += 1;
    lbl81F = gtk_label_new("");
    lbl82F = gtk_label_new("");
    lbl83F = gtk_label_new("");
    lbl84F = gtk_label_new("");
    lbl85F = gtk_label_new("");
    lbl82Fa = gtk_label_new("");
    lbl83Fa = gtk_label_new("");
    lbl84Fa = gtk_label_new("");
    lbl85Fa = gtk_label_new("");
    lbl81G = gtk_label_new("");
    lbl82G = gtk_label_new("");
    lbl83G = gtk_label_new("");
    lbl84G = gtk_label_new("");
    lbl85G = gtk_label_new("");
    lbl81L = gtk_label_new("");
    lbl82L = gtk_label_new("");
    lbl83L = gtk_label_new("");
    lbl84L = gtk_label_new("");
    lbl85L = gtk_label_new("");
    lbl81Gr = gtk_label_new("");
    lbl82Gr = gtk_label_new("");
    lbl83Gr = gtk_label_new("");
    lbl84Gr = gtk_label_new("");
    lbl85Gr = gtk_label_new("");
    gtk_widget_set_size_request(btn81, KEY_WIDTH_1, 0);
    gtk_widget_set_size_request(btn82, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn83, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn84, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn85, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn82A, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn83A, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn84A, KEY_WIDTH_2, 0);
    gtk_widget_set_size_request(btn85A, KEY_WIDTH_2, 0);
    sig(btn81, "button-press-event", @ptrCast(&z47_btnPressed_signal), "32");
    sig(btn82, "button-press-event", @ptrCast(&z47_btnPressed_signal), "33");
    sig(btn83, "button-press-event", @ptrCast(&z47_btnPressed_signal), "34");
    sig(btn84, "button-press-event", @ptrCast(&z47_btnPressed_signal), "35");
    sig(btn85, "button-press-event", @ptrCast(&z47_btnPressed_signal), "36");
    sig(btn81, "button-release-event", @ptrCast(&z47_btnReleased_signal), "32");
    sig(btn82, "button-release-event", @ptrCast(&z47_btnReleased_signal), "33");
    sig(btn83, "button-release-event", @ptrCast(&z47_btnReleased_signal), "34");
    sig(btn84, "button-release-event", @ptrCast(&z47_btnReleased_signal), "35");
    sig(btn85, "button-release-event", @ptrCast(&z47_btnReleased_signal), "36");
    sig(btn82A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "33");
    sig(btn83A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "34");
    sig(btn84A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "35");
    sig(btn85A, "button-press-event", @ptrCast(&z47_btnPressed_signal), "36");
    sig(btn82A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "33");
    sig(btn83A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "34");
    sig(btn84A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "35");
    sig(btn85A, "button-release-event", @ptrCast(&z47_btnReleased_signal), "36");
    gtk_fixed_put(grid, lbl81F, 0, 0);
    gtk_fixed_put(grid, lbl82F, 0, 0);
    gtk_fixed_put(grid, lbl83F, 0, 0);
    gtk_fixed_put(grid, lbl84F, 0, 0);
    gtk_fixed_put(grid, lbl85F, 0, 0);
    gtk_fixed_put(grid, lbl82Fa, 0, 0);
    gtk_fixed_put(grid, lbl83Fa, 0, 0);
    gtk_fixed_put(grid, lbl84Fa, 0, 0);
    gtk_fixed_put(grid, lbl85Fa, 0, 0);
    gtk_fixed_put(grid, lbl81G, 0, 0);
    gtk_fixed_put(grid, lbl82G, 0, 0);
    gtk_fixed_put(grid, lbl83G, 0, 0);
    gtk_fixed_put(grid, lbl84G, 0, 0);
    gtk_fixed_put(grid, lbl85G, 0, 0);
    gtk_fixed_put(grid, lbl81Gr, 0, 0);
    gtk_fixed_put(grid, lbl82Gr, 0, 0);
    gtk_fixed_put(grid, lbl83Gr, 0, 0);
    gtk_fixed_put(grid, lbl84Gr, 0, 0);
    gtk_fixed_put(grid, lbl85Gr, 0, 0);
    xPos = if (calcLandscape) X_LEFT_LANDSCAPE else X_LEFT_PORTRAIT;
    yPos += DELTA_KEYS_Y + 1;
    gtk_fixed_put(grid, btn81, xPos, yPos);
    gtk_fixed_move(grid, lbl81G, xPos + KEY_WIDTH_1 + X_OFFSET_LETTER, yPos + 38);
    xPos += DELTA_KEYS_X + LARGE_KEY_SPACING_1;
    gtk_fixed_put(grid, btn82, xPos, yPos);
    gtk_fixed_put(grid, lbl82L, xPos + KEY_WIDTH_2 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn82A, xPos, yPos);
    xPos += DELTA_KEYS_X + LARGE_KEY_SPACING_2;
    gtk_fixed_put(grid, btn83, xPos, yPos);
    gtk_fixed_put(grid, lbl83L, xPos + KEY_WIDTH_2 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn83A, xPos, yPos);
    xPos += DELTA_KEYS_X + LARGE_KEY_SPACING_2;
    gtk_fixed_put(grid, btn84, xPos, yPos);
    gtk_fixed_put(grid, lbl84L, xPos + KEY_WIDTH_2 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn84A, xPos, yPos);
    xPos += DELTA_KEYS_X + LARGE_KEY_SPACING_2;
    gtk_fixed_put(grid, btn85, xPos, yPos);
    gtk_fixed_put(grid, lbl85L, xPos + KEY_WIDTH_2 + X_OFFSET_LETTER, yPos + Y_OFFSET_LETTER);
    gtk_fixed_put(grid, btn85A, xPos, yPos);

    gtk_widget_show_all(frmCalc);

    lcd_buffer = @as([*c]u8, @ptrCast(malloc(SCREEN_HEIGHT * (SCREEN_WIDTH / 8 + 2) + 2))) + 2;
    lcd_clear_buf();

    check_all_btn_widgets_for_consistency();
}
