// SPDX-License-Identifier: GPL-3.0-only

#include <stdint.h>

void z47_math_wrappers_retained_fnAdd(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnSubtract(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnMultiply(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnDivide(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnIDiv(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnIDivR(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnDblMultiply(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnDblDivide(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnDblDivideRemainder(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnRound(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnDecomp(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnCheckInteger(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnDec(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnInc(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnXLessThan(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnXLessEqual(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnXGreaterThan(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnXGreaterEqual(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnXEqualsTo(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnXNotEqual(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnXAlmostEqual(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnIsConverged(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnCheckType(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnCheckReal(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnCheckNumber(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnCheckAngle(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnCheckMatrix(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnCheckMatrixSquare(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnCheckForZero(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnCheckIsVect2d(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnCheckIsVect3d(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnCheckNaN(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnCheckInfinite(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnCheckSpecial(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnCheckPlusZero(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnCheckMinusZero(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnGetType(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnToPolar2(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnToRect2(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnToRect(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnParallel(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnUnitVector(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnSdl(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnSdr(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnSquareRoot(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnCubeRoot(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnPercentMRR(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnPercentPlusMG(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnPercentT(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnDeltaPercent(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnFib(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnLINPOL(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnCross(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnDot(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
void z47_math_wrappers_retained_fnLogXY(uint16_t unusedButMandatoryParameter) { (void)unusedButMandatoryParameter; }
