pub extern fn z47_frontier_legacy_fnP_Sigma(unused_but_mandatory_parameter: u16) void;
pub extern fn z47_frontier_legacy_fnP_All_Regs(option: u16) void;
pub extern fn z47_frontier_legacy_fnEditMatrix(regist: u16) void;
pub extern fn z47_frontier_legacy_fnOldMatrix(unused_param_but_mandatory: u16) void;
pub extern fn z47_frontier_legacy_fnGoToElement(unused_param_but_mandatory: u16) void;
pub extern fn z47_frontier_legacy_fnGoToRow(row: u16) void;
pub extern fn z47_frontier_legacy_fnGoToColumn(col: u16) void;
pub extern fn z47_frontier_legacy_fnSetGrowMode(grow_flag: u16) void;
pub extern fn z47_frontier_legacy_fnIncDecI(mode: u16) void;
pub extern fn z47_frontier_legacy_fnIncDecJ(mode: u16) void;
pub extern fn z47_frontier_legacy_fnInsRow(unused_param_but_mandatory: u16) void;
pub extern fn z47_frontier_legacy_fnAddRow(unused_param_but_mandatory: u16) void;
pub extern fn z47_frontier_legacy_fnInsCol(unused_param_but_mandatory: u16) void;
pub extern fn z47_frontier_legacy_fnAddCol(unused_param_but_mandatory: u16) void;
pub extern fn z47_frontier_legacy_fnDelRow(unused_param_but_mandatory: u16) void;
pub extern fn z47_frontier_legacy_fnDelCol(unused_param_but_mandatory: u16) void;
pub extern fn z47_frontier_legacy_mimAddNumber(item: i16) void;
pub extern fn z47_frontier_legacy_mimRunFunction(func: i16, param: u16) void;
