#!/usr/bin/env python3
"""Phase A: audit C dependency allowlist and first-party baseline.

This tool scans build wiring files for path-like string literals used by C wiring,
classifies them, and fails if new first-party entries are introduced relative to
a checked-in baseline file.
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import re
import sys
from pathlib import Path

STRING_RE = re.compile(r'"([^"\\]*(?:\\.[^"\\]*)*)"')


def load_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def normalize_path(value: str) -> str:
    value = value.replace("\\\\", "/")
    value = value.strip()
    while value.startswith("./"):
        value = value[2:]
    return value


def candidate_literals_from_file(path: Path) -> set[str]:
    text = path.read_text(encoding="utf-8", errors="ignore")
    found: set[str] = set()
    for m in STRING_RE.finditer(text):
        raw = m.group(1)
        literal = normalize_path(raw)
        if "/" not in literal:
            continue
        if ".c" not in literal and not literal.startswith(("src/", "dep/", "zig_bridge/", "generated/", "zig_build/")):
            continue
        found.add(literal)
    return found


def classify_entry(entry: str, cfg: dict) -> str:
    external = tuple(cfg.get("allowed_external_prefixes", []))
    first_party = tuple(cfg.get("first_party_prefixes", []))
    generated = tuple(cfg.get("generated_prefixes", []))
    ignored = tuple(cfg.get("ignored_prefixes", []))

    if entry.startswith(ignored):
        return "ignored"

    if entry.startswith(external):
        return "external"
    if entry.startswith(first_party):
        return "first-party"
    if entry.startswith(generated):
        return "generated"
    if entry.endswith(".c"):
        return "first-party"
    return "other"


def resolve_scan_files(repo_root: Path, cfg: dict) -> list[Path]:
    files: list[Path] = []
    for pattern in cfg.get("scan_globs", []):
        full_pattern = str(repo_root / pattern)
        for match in glob.glob(full_pattern, recursive=True):
            p = Path(match)
            if p.is_file():
                files.append(p)
    return sorted(set(files))


def load_baseline(path: Path) -> set[str]:
    if not path.exists():
        return set()
    out: set[str] = set()
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        out.add(line)
    return out


def write_baseline(path: Path, entries: set[str]) -> None:
    lines = [
        "# First-party C dependency baseline entries (Phase A)",
        "# Auto-generated by .github/project/check-c-dependency-allowlist.py --update-baseline",
        "",
    ]
    lines.extend(sorted(entries))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Audit C dependency allowlist and first-party baseline")
    parser.add_argument("--repo-root", default=".", help="Repository root path")
    parser.add_argument("--config", required=True, help="Path to JSON allowlist config")
    parser.add_argument("--update-baseline", action="store_true", help="Rewrite baseline from current scan")
    parser.add_argument("--max-first-party", type=int, default=None, help="Fail if detected first-party entries exceed this value")
    parser.add_argument(
        "--print-first-party-count",
        action="store_true",
        help="Print detected first-party entry count and exit",
    )
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    config_path = (repo_root / args.config).resolve() if not os.path.isabs(args.config) else Path(args.config)
    cfg = load_json(config_path)

    scan_files = resolve_scan_files(repo_root, cfg)
    entries: set[str] = set()
    for f in scan_files:
        entries.update(candidate_literals_from_file(f))

    classified: dict[str, set[str]] = {
        "external": set(),
        "first-party": set(),
        "generated": set(),
        "ignored": set(),
        "other": set(),
    }
    for e in entries:
        classified[classify_entry(e, cfg)].add(e)

    baseline_rel = cfg.get("baseline_file")
    if not baseline_rel:
        print("ERROR: baseline_file is missing in config", file=sys.stderr)
        return 2
    baseline_path = (repo_root / baseline_rel).resolve()

    if args.print_first_party_count:
        print(len(classified["first-party"]))
        return 0

    if args.update_baseline:
        write_baseline(baseline_path, classified["first-party"])
        print(f"Updated baseline: {baseline_path}")
        print(f"First-party entries: {len(classified['first-party'])}")
        return 0

    baseline = load_baseline(baseline_path)
    new_first_party = sorted(classified["first-party"] - baseline)

    print("C dependency audit summary")
    print(f"- scanned files: {len(scan_files)}")
    print(f"- external entries: {len(classified['external'])}")
    print(f"- first-party entries: {len(classified['first-party'])}")
    print(f"- generated entries: {len(classified['generated'])}")
    print(f"- ignored entries: {len(classified['ignored'])}")
    print("- unknown-c entries: 0")

    if new_first_party:
        print("\nERROR: new first-party C dependency entries detected:")
        for e in new_first_party:
            print(f"  {e}")
        print("\nIf intentional, update baseline with:")
        print("  python3 .github/project/check-c-dependency-allowlist.py --repo-root . --config .github/project/c-dependency-allowlist.json --update-baseline")
        return 1

    if args.max_first_party is not None and len(classified["first-party"]) > args.max_first_party:
        print("\nERROR: first-party C dependency cap exceeded:")
        print(f"  detected={len(classified['first-party'])} cap={args.max_first_party}")
        return 1

    print("\nPASS: no new first-party C dependency entries detected.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
