// SPDX-License-Identifier: GPL-3.0-only

#define getRegisterDataType z47_registers_retained_getRegisterDataType
#define getRegisterDataPointer z47_registers_retained_getRegisterDataPointer
#define getRegisterTag z47_registers_retained_getRegisterTag
#define setRegisterDataType z47_registers_retained_setRegisterDataType
#define setRegisterDataPointer z47_registers_retained_setRegisterDataPointer
#define setRegisterTag z47_registers_retained_setRegisterTag
#define allocateLocalRegisters z47_registers_retained_allocateLocalRegisters
#define validateName z47_registers_retained_validateName
#define isUniqueMenuName z47_registers_retained_isUniqueMenuName
#define allocateNamedVariable z47_registers_retained_allocateNamedVariable
#define fnDeleteVariable z47_registers_retained_fnDeleteVariable
#define fnDeleteAllVariables z47_registers_retained_fnDeleteAllVariables
#define fnClearAllVariables z47_registers_retained_fnClearAllVariables
#define setRegisterMaxDataLengthInBlocks z47_registers_retained_setRegisterMaxDataLengthInBlocks
#define getRegisterMaxDataLengthInBlocks z47_registers_retained_getRegisterMaxDataLengthInBlocks
#define getRegisterFullSizeInBlocks z47_registers_retained_getRegisterFullSizeInBlocks
#define clearRegister z47_registers_retained_clearRegister
#define fnClearRegisters z47_registers_retained_fnClearRegisters
#define fnGetLocR z47_registers_retained_fnGetLocR
#define adjustResult z47_registers_retained_adjustResult
#define copySourceRegisterToDestRegister z47_registers_retained_copySourceRegisterToDestRegister
#define reallocateRegister z47_registers_retained_reallocateRegister
#define fnToReal z47_registers_retained_fnToReal
#define saveLastX z47_registers_retained_saveLastX
#define fnRegClr z47_registers_retained_fnRegClr
#define fnRegSort z47_registers_retained_fnRegSort
#define fnRegCopy z47_registers_retained_fnRegCopy
#define fnRegSwap z47_registers_retained_fnRegSwap
#define isFunctionAllowingNewVariable z47_registers_retained_isFunctionAllowingNewVariable

#include "../../src/c47/registers.c"