// SPDX-License-Identifier: GPL-3.0-only

#define getRegisterDataType z47_registers_legacy_getRegisterDataType
#define getRegisterDataPointer z47_registers_legacy_getRegisterDataPointer
#define getRegisterTag z47_registers_legacy_getRegisterTag
#define setRegisterDataType z47_registers_legacy_setRegisterDataType
#define setRegisterDataPointer z47_registers_legacy_setRegisterDataPointer
#define setRegisterTag z47_registers_legacy_setRegisterTag
#define allocateLocalRegisters z47_registers_legacy_allocateLocalRegisters
#define validateName z47_registers_legacy_validateName
#define isUniqueMenuName z47_registers_legacy_isUniqueMenuName
#define allocateNamedVariable z47_registers_legacy_allocateNamedVariable
#define findNamedVariable z47_registers_legacy_findNamedVariable
#define findOrAllocateNamedVariable z47_registers_legacy_findOrAllocateNamedVariable
#define fnDeleteVariable z47_registers_legacy_fnDeleteVariable
#define fnDeleteAllVariables z47_registers_legacy_fnDeleteAllVariables
#define fnClearAllVariables z47_registers_legacy_fnClearAllVariables
#define setRegisterMaxDataLengthInBlocks z47_registers_legacy_setRegisterMaxDataLengthInBlocks
#define getRegisterMaxDataLengthInBlocks z47_registers_legacy_getRegisterMaxDataLengthInBlocks
#define getRegisterFullSizeInBlocks z47_registers_legacy_getRegisterFullSizeInBlocks
#define clearRegister z47_registers_legacy_clearRegister
#define fnClearRegisters z47_registers_legacy_fnClearRegisters
#define fnGetLocR z47_registers_legacy_fnGetLocR
#define adjustResult z47_registers_legacy_adjustResult
#define copySourceRegisterToDestRegister z47_registers_legacy_copySourceRegisterToDestRegister
#define reallocateRegister z47_registers_legacy_reallocateRegister
#define fnToReal z47_registers_legacy_fnToReal
#define saveLastX z47_registers_legacy_saveLastX
#define fnRegClr z47_registers_legacy_fnRegClr
#define fnRegSort z47_registers_legacy_fnRegSort
#define fnRegCopy z47_registers_legacy_fnRegCopy
#define fnRegSwap z47_registers_legacy_fnRegSwap
#define isFunctionAllowingNewVariable z47_registers_legacy_isFunctionAllowingNewVariable

#include "../../src/c47/registers.c"

uint8_t z47_registers_legacy_get_reg_clr_range(uint16_t *s, uint16_t *n) {
	return getRegParam(NULL, s, n, NULL);
}

uint8_t z47_registers_legacy_get_reg_swap_range(uint16_t *s, uint16_t *n, uint16_t *d) {
	return getRegParam(NULL, s, n, d);
}

uint8_t z47_registers_legacy_get_reg_copy_params(bool_t *f, uint16_t *s, uint16_t *n, uint16_t *d) {
	return getRegParam(f, s, n, d);
}

void z47_registers_legacy_sort_reg(uint16_t range_start, uint16_t range_end) {
	sortReg(range_start, range_end);
}